//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class ArrayOfAppointment;
#import "MBRequest.h"
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface AddOrUpdateAppointmentsRequest : MBRequest 


@property (retain,nonatomic,getter=getUpdateAction) NSString* UpdateAction;

@property (retain,nonatomic,getter=getTest) NSString* Test;

@property (retain,nonatomic,getter=getSendEmail) NSString* SendEmail;

@property (retain,nonatomic,getter=getApplyPayment) NSString* ApplyPayment;

@property (retain,nonatomic,getter=getAppointments) ArrayOfAppointment* Appointments;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(AddOrUpdateAppointmentsRequest*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end