//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class ArrayOfInt;
@class ArrayOfLong;
@class ArrayOfDayOfWeek;
#import "MBRequest.h"
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface AddOrUpdateAvailabilitiesRequest : MBRequest 


@property (retain,nonatomic,getter=getUpdateAction) NSString* UpdateAction;

@property (retain,nonatomic,getter=getTest) NSString* Test;

@property (retain,nonatomic,getter=getAvailabilityIDs) ArrayOfInt* AvailabilityIDs;

@property (retain,nonatomic,getter=getLocationID) NSString* LocationID;

@property (retain,nonatomic,getter=getStaffIDs) ArrayOfLong* StaffIDs;

@property (retain,nonatomic,getter=getProgramIDs) ArrayOfInt* ProgramIDs;

@property (retain,nonatomic,getter=getStartDateTime) NSString* StartDateTime;

@property (retain,nonatomic,getter=getEndDateTime) NSString* EndDateTime;

@property (retain,nonatomic,getter=getDaysOfWeek) ArrayOfDayOfWeek* DaysOfWeek;

@property (retain,nonatomic,getter=getUnavailableDescription) NSString* UnavailableDescription;

@property (retain,nonatomic,getter=getIsUnavailable) NSString* IsUnavailable;

@property (retain,nonatomic,getter=getPublicDisplay) NSString* PublicDisplay;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(AddOrUpdateAvailabilitiesRequest*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end