//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "ArrayOfInt.h"
#import "ArrayOfLong.h"
#import "ArrayOfDayOfWeek.h"
#import "MBRequest.h"
#import "Helper.h"
#import "AddOrUpdateAvailabilitiesRequest.h"


@implementation AddOrUpdateAvailabilitiesRequest
    @synthesize UpdateAction;
    @synthesize Test;
    @synthesize AvailabilityIDs;
    @synthesize LocationID;
    @synthesize StaffIDs;
    @synthesize ProgramIDs;
    @synthesize StartDateTime;
    @synthesize EndDateTime;
    @synthesize DaysOfWeek;
    @synthesize UnavailableDescription;
    @synthesize IsUnavailable;
    @synthesize PublicDisplay;

+ (AddOrUpdateAvailabilitiesRequest *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"UpdateAction"])
        {
            self.UpdateAction = [[Helper getNode:__node name:@"UpdateAction"] stringValue];
        }
        if([Helper hasValue:__node name:@"Test"])
        {
            self.Test = [[Helper getNode:__node name:@"Test"] stringValue];
        }
        if([Helper hasValue:__node name:@"AvailabilityIDs"])
        {
            self.AvailabilityIDs = (ArrayOfInt*)[__request createObject:[Helper getNode:__node name:@"AvailabilityIDs"] type:[ArrayOfInt class]];
        }
        if([Helper hasValue:__node name:@"LocationID"])
        {
            self.LocationID = [[Helper getNode:__node name:@"LocationID"] stringValue];
        }
        if([Helper hasValue:__node name:@"StaffIDs"])
        {
            self.StaffIDs = (ArrayOfLong*)[__request createObject:[Helper getNode:__node name:@"StaffIDs"] type:[ArrayOfLong class]];
        }
        if([Helper hasValue:__node name:@"ProgramIDs"])
        {
            self.ProgramIDs = (ArrayOfInt*)[__request createObject:[Helper getNode:__node name:@"ProgramIDs"] type:[ArrayOfInt class]];
        }
        if([Helper hasValue:__node name:@"StartDateTime"])
        {
            self.StartDateTime = [[Helper getNode:__node name:@"StartDateTime"] stringValue];
        }
        if([Helper hasValue:__node name:@"EndDateTime"])
        {
            self.EndDateTime = [[Helper getNode:__node name:@"EndDateTime"] stringValue];
        }
        if([Helper hasValue:__node name:@"DaysOfWeek"])
        {
            self.DaysOfWeek = (ArrayOfDayOfWeek*)[__request createObject:[Helper getNode:__node name:@"DaysOfWeek"] type:[ArrayOfDayOfWeek class]];
        }
        if([Helper hasValue:__node name:@"UnavailableDescription"])
        {
            self.UnavailableDescription = [[Helper getNode:__node name:@"UnavailableDescription"] stringValue];
        }
        if([Helper hasValue:__node name:@"IsUnavailable"])
        {
            self.IsUnavailable = [[Helper getNode:__node name:@"IsUnavailable"] stringValue];
        }
        if([Helper hasValue:__node name:@"PublicDisplay"])
        {
            self.PublicDisplay = [[Helper getNode:__node name:@"PublicDisplay"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __UpdateActionItemElement=[__request writeElement:UpdateAction type:[NSString class] name:@"UpdateAction" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__UpdateActionItemElement!=nil)
        {
            [__UpdateActionItemElement setStringValue:self.UpdateAction];
        }
             
        DDXMLElement* __TestItemElement=[__request writeElement:Test type:[NSString class] name:@"Test" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__TestItemElement!=nil)
        {
            [__TestItemElement setStringValue:self.Test];
        }
             
        DDXMLElement* __AvailabilityIDsItemElement=[__request writeElement:AvailabilityIDs type:[ArrayOfInt class] name:@"AvailabilityIDs" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AvailabilityIDsItemElement!=nil)
        {
            [self.AvailabilityIDs serialize:__AvailabilityIDsItemElement __request: __request];
        }
             
        DDXMLElement* __LocationIDItemElement=[__request writeElement:LocationID type:[NSString class] name:@"LocationID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LocationIDItemElement!=nil)
        {
            [__LocationIDItemElement setStringValue:self.LocationID];
        }
             
        DDXMLElement* __StaffIDsItemElement=[__request writeElement:StaffIDs type:[ArrayOfLong class] name:@"StaffIDs" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StaffIDsItemElement!=nil)
        {
            [self.StaffIDs serialize:__StaffIDsItemElement __request: __request];
        }
             
        DDXMLElement* __ProgramIDsItemElement=[__request writeElement:ProgramIDs type:[ArrayOfInt class] name:@"ProgramIDs" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ProgramIDsItemElement!=nil)
        {
            [self.ProgramIDs serialize:__ProgramIDsItemElement __request: __request];
        }
             
        DDXMLElement* __StartDateTimeItemElement=[__request writeElement:StartDateTime type:[NSString class] name:@"StartDateTime" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StartDateTimeItemElement!=nil)
        {
            [__StartDateTimeItemElement setStringValue:self.StartDateTime];
        }
             
        DDXMLElement* __EndDateTimeItemElement=[__request writeElement:EndDateTime type:[NSString class] name:@"EndDateTime" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EndDateTimeItemElement!=nil)
        {
            [__EndDateTimeItemElement setStringValue:self.EndDateTime];
        }
             
        DDXMLElement* __DaysOfWeekItemElement=[__request writeElement:DaysOfWeek type:[ArrayOfDayOfWeek class] name:@"DaysOfWeek" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__DaysOfWeekItemElement!=nil)
        {
            [self.DaysOfWeek serialize:__DaysOfWeekItemElement __request: __request];
        }
             
        DDXMLElement* __UnavailableDescriptionItemElement=[__request writeElement:UnavailableDescription type:[NSString class] name:@"UnavailableDescription" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__UnavailableDescriptionItemElement!=nil)
        {
            [__UnavailableDescriptionItemElement setStringValue:self.UnavailableDescription];
        }
             
        DDXMLElement* __IsUnavailableItemElement=[__request writeElement:IsUnavailable type:[NSString class] name:@"IsUnavailable" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IsUnavailableItemElement!=nil)
        {
            [__IsUnavailableItemElement setStringValue:self.IsUnavailable];
        }
             
        DDXMLElement* __PublicDisplayItemElement=[__request writeElement:PublicDisplay type:[NSString class] name:@"PublicDisplay" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PublicDisplayItemElement!=nil)
        {
            [__PublicDisplayItemElement setStringValue:self.PublicDisplay];
        }


}
@end
