//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "ArrayOfAppointment.h"
#import "MBRequest.h"
#import "Helper.h"
#import "AddOrUpdateAppointmentsRequest.h"


@implementation AddOrUpdateAppointmentsRequest
    @synthesize UpdateAction;
    @synthesize Test;
    @synthesize SendEmail;
    @synthesize ApplyPayment;
    @synthesize Appointments;

+ (AddOrUpdateAppointmentsRequest *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"UpdateAction"])
        {
            self.UpdateAction = [[Helper getNode:__node name:@"UpdateAction"] stringValue];
        }
        if([Helper hasValue:__node name:@"Test"])
        {
            self.Test = [[Helper getNode:__node name:@"Test"] stringValue];
        }
        if([Helper hasValue:__node name:@"SendEmail"])
        {
            self.SendEmail = [[Helper getNode:__node name:@"SendEmail"] stringValue];
        }
        if([Helper hasValue:__node name:@"ApplyPayment"])
        {
            self.ApplyPayment = [[Helper getNode:__node name:@"ApplyPayment"] stringValue];
        }
        if([Helper hasValue:__node name:@"Appointments"])
        {
            self.Appointments = (ArrayOfAppointment*)[__request createObject:[Helper getNode:__node name:@"Appointments"] type:[ArrayOfAppointment class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __UpdateActionItemElement=[__request writeElement:UpdateAction type:[NSString class] name:@"UpdateAction" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__UpdateActionItemElement!=nil)
        {
            [__UpdateActionItemElement setStringValue:self.UpdateAction];
        }
             
        DDXMLElement* __TestItemElement=[__request writeElement:Test type:[NSString class] name:@"Test" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__TestItemElement!=nil)
        {
            [__TestItemElement setStringValue:self.Test];
        }
             
        DDXMLElement* __SendEmailItemElement=[__request writeElement:SendEmail type:[NSString class] name:@"SendEmail" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__SendEmailItemElement!=nil)
        {
            [__SendEmailItemElement setStringValue:self.SendEmail];
        }
             
        DDXMLElement* __ApplyPaymentItemElement=[__request writeElement:ApplyPayment type:[NSString class] name:@"ApplyPayment" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ApplyPaymentItemElement!=nil)
        {
            [__ApplyPaymentItemElement setStringValue:self.ApplyPayment];
        }
             
        DDXMLElement* __AppointmentsItemElement=[__request writeElement:Appointments type:[ArrayOfAppointment class] name:@"Appointments" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AppointmentsItemElement!=nil)
        {
            [self.Appointments serialize:__AppointmentsItemElement __request: __request];
        }


}
@end
