//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class Program;
@class SessionType;
@class Location;
@class Staff;
@class Client;
@class ClientService;
@class ArrayOfResource;
#import "ScheduleItem.h"
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface Appointment : ScheduleItem 


@property (retain,nonatomic,getter=getGenderPreference) NSString* GenderPreference;

@property (retain,nonatomic,getter=getDuration) NSString* Duration;

@property (retain,nonatomic,getter=getAction) NSString* Action;

@property (retain,nonatomic,getter=getID) NSString* ID;

@property (retain,nonatomic,getter=getStatus) NSString* Status;

@property (retain,nonatomic,getter=getStartDateTime) NSString* StartDateTime;

@property (retain,nonatomic,getter=getEndDateTime) NSString* EndDateTime;

@property (retain,nonatomic,getter=getNotes) NSString* Notes;

@property (retain,nonatomic,getter=getStaffRequested) NSString* StaffRequested;

@property (retain,nonatomic,getter=getProgram) Program* Program;

@property (retain,nonatomic,getter=getSessionType) SessionType* SessionType;

@property (retain,nonatomic,getter=getLocation) Location* Location;

@property (retain,nonatomic,getter=getStaff) Staff* Staff;

@property (retain,nonatomic,getter=getClient) Client* Client;

@property (retain,nonatomic,getter=getFirstAppointment) NSString* FirstAppointment;

@property (retain,nonatomic,getter=getClientService) ClientService* ClientService;

@property (retain,nonatomic,getter=getResources) ArrayOfResource* Resources;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(Appointment*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end