//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "Appointment_x005F_x0020_ServiceSoap.h"
#import "RequestResultHandler.h"
#import "Helper.h"

@implementation Appointment_x005F_x0020_ServiceSoap
@synthesize Url,ShouldAddAdornments,Headers;

- (id) init {
    if(self = [super init])
    {
        self.Url=@"https://api.mindbodyonline.com/0_5/AppointmentService.asmx";
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(RequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}



-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) createGetStaffAppointmentsRequest:(GetStaffAppointmentsRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"GetStaffAppointments" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[GetStaffAppointmentsRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/GetStaffAppointments";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(GetStaffAppointmentsResult*) GetStaffAppointments:(GetStaffAppointmentsRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    __request.SkipNullProperties = YES;
    
    NSMutableURLRequest *__requestObj=[self createGetStaffAppointmentsRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"GetStaffAppointmentsResult"];
    return (GetStaffAppointmentsResult*)[__request createObject:__result type:[GetStaffAppointmentsResult class]];
}

-(NSMutableURLRequest*) createAddOrUpdateAppointmentsRequest:(AddOrUpdateAppointmentsRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"AddOrUpdateAppointments" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[AddOrUpdateAppointmentsRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/AddOrUpdateAppointments";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(AddOrUpdateAppointmentsResult*) AddOrUpdateAppointments:(AddOrUpdateAppointmentsRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self createAddOrUpdateAppointmentsRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"AddOrUpdateAppointmentsResult"];
    return (AddOrUpdateAppointmentsResult*)[__request createObject:__result type:[AddOrUpdateAppointmentsResult class]];
}
-(NSMutableURLRequest*) createGetBookableItemsRequest:(GetBookableItemsRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"GetBookableItems" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[GetBookableItemsRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/GetBookableItems";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(GetBookableItemsResult*) GetBookableItems:(GetBookableItemsRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self createGetBookableItemsRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"GetBookableItemsResult"];
    return (GetBookableItemsResult*)[__request createObject:__result type:[GetBookableItemsResult class]];
}
-(NSMutableURLRequest*) createGetScheduleItemsRequest:(GetScheduleItemsRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"GetScheduleItems" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[GetScheduleItemsRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/GetScheduleItems";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(GetScheduleItemsResult*) GetScheduleItems:(GetScheduleItemsRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self createGetScheduleItemsRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"GetScheduleItemsResult"];
    return (GetScheduleItemsResult*)[__request createObject:__result type:[GetScheduleItemsResult class]];
}
-(NSMutableURLRequest*) createAddOrUpdateAvailabilitiesRequest:(AddOrUpdateAvailabilitiesRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"AddOrUpdateAvailabilities" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[AddOrUpdateAvailabilitiesRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/AddOrUpdateAvailabilities";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(AddOrUpdateAvailabilitiesResult*) AddOrUpdateAvailabilities:(AddOrUpdateAvailabilitiesRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self createAddOrUpdateAvailabilitiesRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"AddOrUpdateAvailabilitiesResult"];
    return (AddOrUpdateAvailabilitiesResult*)[__request createObject:__result type:[AddOrUpdateAvailabilitiesResult class]];
}
-(NSMutableURLRequest*) createGetActiveSessionTimesRequest:(GetActiveSessionTimesRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"GetActiveSessionTimes" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[GetActiveSessionTimesRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/GetActiveSessionTimes";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(GetActiveSessionTimesResult*) GetActiveSessionTimes:(GetActiveSessionTimesRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self createGetActiveSessionTimesRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"GetActiveSessionTimesResult"];
    return (GetActiveSessionTimesResult*)[__request createObject:__result type:[GetActiveSessionTimesResult class]];
}
-(NSMutableURLRequest*) createGetAppointmentOptionsRequest:(GetAppointmentOptionsRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"GetAppointmentOptions" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[GetAppointmentOptionsRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/GetAppointmentOptions";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(GetAppointmentOptionsResult*) GetAppointmentOptions:(GetAppointmentOptionsRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self createGetAppointmentOptionsRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"GetAppointmentOptionsResult"];
    return (GetAppointmentOptionsResult*)[__request createObject:__result type:[GetAppointmentOptionsResult class]];
}

@end
