//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "Program.h"
#import "SessionType.h"
#import "Location.h"
#import "Staff.h"
#import "Client.h"
#import "ClientService.h"
#import "ArrayOfResource.h"
#import "ScheduleItem.h"
#import "Helper.h"
#import "Appointment.h"


@implementation Appointment
    @synthesize GenderPreference;
    @synthesize Duration;
    @synthesize Action;
    @synthesize ID;
    @synthesize Status;
    @synthesize StartDateTime;
    @synthesize EndDateTime;
    @synthesize Notes;
    @synthesize StaffRequested;
    @synthesize Program;
    @synthesize SessionType;
    @synthesize Location;
    @synthesize Staff;
    @synthesize Client;
    @synthesize FirstAppointment;
    @synthesize ClientService;
    @synthesize Resources;

+ (Appointment *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"GenderPreference"])
        {
            self.GenderPreference = [[Helper getNode:__node name:@"GenderPreference"] stringValue];
        }
        if([Helper hasValue:__node name:@"Duration"])
        {
            self.Duration = [[Helper getNode:__node name:@"Duration"] stringValue];
        }
        if([Helper hasValue:__node name:@"Action"])
        {
            self.Action = [[Helper getNode:__node name:@"Action"] stringValue];
        }
        if([Helper hasValue:__node name:@"ID"])
        {
            self.ID = [[Helper getNode:__node name:@"ID"] stringValue];
        }
        if([Helper hasValue:__node name:@"Status"])
        {
            self.Status = [[Helper getNode:__node name:@"Status"] stringValue];
        }
        if([Helper hasValue:__node name:@"StartDateTime"])
        {
            self.StartDateTime = [[Helper getNode:__node name:@"StartDateTime"] stringValue];
        }
        if([Helper hasValue:__node name:@"EndDateTime"])
        {
            self.EndDateTime = [[Helper getNode:__node name:@"EndDateTime"] stringValue];
        }
        if([Helper hasValue:__node name:@"Notes"])
        {
            self.Notes = [[Helper getNode:__node name:@"Notes"] stringValue];
        }
        if([Helper hasValue:__node name:@"StaffRequested"])
        {
            self.StaffRequested = [[Helper getNode:__node name:@"StaffRequested"] stringValue];
        }
        if([Helper hasValue:__node name:@"Program"])
        {
            self.Program = (Program*)[__request createObject:[Helper getNode:__node name:@"Program"] type:[Program class]];
        }
        if([Helper hasValue:__node name:@"SessionType"])
        {
            self.SessionType = (SessionType*)[__request createObject:[Helper getNode:__node name:@"SessionType"] type:[SessionType class]];
        }
        if([Helper hasValue:__node name:@"Location"])
        {
            self.Location = (Location*)[__request createObject:[Helper getNode:__node name:@"Location"] type:[Location class]];
        }
        if([Helper hasValue:__node name:@"Staff"])
        {
            self.Staff = (Staff*)[__request createObject:[Helper getNode:__node name:@"Staff"] type:[Staff class]];
        }
        if([Helper hasValue:__node name:@"Client"])
        {
            self.Client = (Client*)[__request createObject:[Helper getNode:__node name:@"Client"] type:[Client class]];
        }
        if([Helper hasValue:__node name:@"FirstAppointment"])
        {
            self.FirstAppointment = [[Helper getNode:__node name:@"FirstAppointment"] stringValue];
        }
        if([Helper hasValue:__node name:@"ClientService"])
        {
            self.ClientService = (ClientService*)[__request createObject:[Helper getNode:__node name:@"ClientService"] type:[ClientService class]];
        }
        if([Helper hasValue:__node name:@"Resources"])
        {
            self.Resources = (ArrayOfResource*)[__request createObject:[Helper getNode:__node name:@"Resources"] type:[ArrayOfResource class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __GenderPreferenceItemElement=[__request writeElement:GenderPreference type:[NSString class] name:@"GenderPreference" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__GenderPreferenceItemElement!=nil)
        {
            [__GenderPreferenceItemElement setStringValue:self.GenderPreference];
        }
             
        DDXMLElement* __DurationItemElement=[__request writeElement:Duration type:[NSString class] name:@"Duration" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__DurationItemElement!=nil)
        {
            [__DurationItemElement setStringValue:self.Duration];
        }
             
        DDXMLElement* __ActionItemElement=[__request writeElement:Action type:[NSString class] name:@"Action" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ActionItemElement!=nil)
        {
            [__ActionItemElement setStringValue:self.Action];
        }
             
        DDXMLElement* __IDItemElement=[__request writeElement:ID type:[NSString class] name:@"ID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IDItemElement!=nil)
        {
            [__IDItemElement setStringValue:self.ID];
        }
             
        DDXMLElement* __StatusItemElement=[__request writeElement:Status type:[NSString class] name:@"Status" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StatusItemElement!=nil)
        {
            [__StatusItemElement setStringValue:self.Status];
        }
             
        DDXMLElement* __StartDateTimeItemElement=[__request writeElement:StartDateTime type:[NSString class] name:@"StartDateTime" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StartDateTimeItemElement!=nil)
        {
            [__StartDateTimeItemElement setStringValue:self.StartDateTime];
        }
             
        DDXMLElement* __EndDateTimeItemElement=[__request writeElement:EndDateTime type:[NSString class] name:@"EndDateTime" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EndDateTimeItemElement!=nil)
        {
            [__EndDateTimeItemElement setStringValue:self.EndDateTime];
        }
             
        DDXMLElement* __NotesItemElement=[__request writeElement:Notes type:[NSString class] name:@"Notes" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__NotesItemElement!=nil)
        {
            [__NotesItemElement setStringValue:self.Notes];
        }
             
        DDXMLElement* __StaffRequestedItemElement=[__request writeElement:StaffRequested type:[NSString class] name:@"StaffRequested" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StaffRequestedItemElement!=nil)
        {
            [__StaffRequestedItemElement setStringValue:self.StaffRequested];
        }
             
        DDXMLElement* __ProgramItemElement=[__request writeElement:Program type:[Program class] name:@"Program" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ProgramItemElement!=nil)
        {
            [self.Program serialize:__ProgramItemElement __request: __request];
        }
             
        DDXMLElement* __SessionTypeItemElement=[__request writeElement:SessionType type:[SessionType class] name:@"SessionType" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__SessionTypeItemElement!=nil)
        {
            [self.SessionType serialize:__SessionTypeItemElement __request: __request];
        }
             
        DDXMLElement* __LocationItemElement=[__request writeElement:Location type:[Location class] name:@"Location" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LocationItemElement!=nil)
        {
            [self.Location serialize:__LocationItemElement __request: __request];
        }
             
        DDXMLElement* __StaffItemElement=[__request writeElement:Staff type:[Staff class] name:@"Staff" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StaffItemElement!=nil)
        {
            [self.Staff serialize:__StaffItemElement __request: __request];
        }
             
        DDXMLElement* __ClientItemElement=[__request writeElement:Client type:[Client class] name:@"Client" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ClientItemElement!=nil)
        {
            [self.Client serialize:__ClientItemElement __request: __request];
        }
             
        DDXMLElement* __FirstAppointmentItemElement=[__request writeElement:FirstAppointment type:[NSString class] name:@"FirstAppointment" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__FirstAppointmentItemElement!=nil)
        {
            [__FirstAppointmentItemElement setStringValue:self.FirstAppointment];
        }
             
        DDXMLElement* __ClientServiceItemElement=[__request writeElement:ClientService type:[ClientService class] name:@"ClientService" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ClientServiceItemElement!=nil)
        {
            [self.ClientService serialize:__ClientServiceItemElement __request: __request];
        }
             
        DDXMLElement* __ResourcesItemElement=[__request writeElement:Resources type:[ArrayOfResource class] name:@"Resources" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ResourcesItemElement!=nil)
        {
            [self.Resources serialize:__ResourcesItemElement __request: __request];
        }


}
@end
