//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "GetStaffAppointmentsResult.h"
#import "GetStaffAppointmentsRequest.h"
#import "AddOrUpdateAppointmentsResult.h"
#import "AddOrUpdateAppointmentsRequest.h"
#import "GetBookableItemsResult.h"
#import "GetBookableItemsRequest.h"
#import "GetScheduleItemsResult.h"
#import "GetScheduleItemsRequest.h"
#import "AddOrUpdateAvailabilitiesResult.h"
#import "AddOrUpdateAvailabilitiesRequest.h"
#import "GetActiveSessionTimesResult.h"
#import "GetActiveSessionTimesRequest.h"
#import "GetAppointmentOptionsResult.h"
#import "GetAppointmentOptionsRequest.h"
#import "DDXML.h"

@class RequestResultHandler;



@interface Appointment_x005F_x0020_ServiceSoap : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) createGetStaffAppointmentsRequest:(GetStaffAppointmentsRequest*) Request __request:(RequestResultHandler*) __request;
-(GetStaffAppointmentsResult*) GetStaffAppointments:(GetStaffAppointmentsRequest*) Request __error:(NSError**) __error;
-(NSMutableURLRequest*) createAddOrUpdateAppointmentsRequest:(AddOrUpdateAppointmentsRequest*) Request __request:(RequestResultHandler*) __request;
-(AddOrUpdateAppointmentsResult*) AddOrUpdateAppointments:(AddOrUpdateAppointmentsRequest*) Request __error:(NSError**) __error;
-(NSMutableURLRequest*) createGetBookableItemsRequest:(GetBookableItemsRequest*) Request __request:(RequestResultHandler*) __request;
-(GetBookableItemsResult*) GetBookableItems:(GetBookableItemsRequest*) Request __error:(NSError**) __error;
-(NSMutableURLRequest*) createGetScheduleItemsRequest:(GetScheduleItemsRequest*) Request __request:(RequestResultHandler*) __request;
-(GetScheduleItemsResult*) GetScheduleItems:(GetScheduleItemsRequest*) Request __error:(NSError**) __error;
-(NSMutableURLRequest*) createAddOrUpdateAvailabilitiesRequest:(AddOrUpdateAvailabilitiesRequest*) Request __request:(RequestResultHandler*) __request;
-(AddOrUpdateAvailabilitiesResult*) AddOrUpdateAvailabilities:(AddOrUpdateAvailabilitiesRequest*) Request __error:(NSError**) __error;
-(NSMutableURLRequest*) createGetActiveSessionTimesRequest:(GetActiveSessionTimesRequest*) Request __request:(RequestResultHandler*) __request;
-(GetActiveSessionTimesResult*) GetActiveSessionTimes:(GetActiveSessionTimesRequest*) Request __error:(NSError**) __error;
-(NSMutableURLRequest*) createGetAppointmentOptionsRequest:(GetAppointmentOptionsRequest*) Request __request:(RequestResultHandler*) __request;
-(GetAppointmentOptionsResult*) GetAppointmentOptions:(GetAppointmentOptionsRequest*) Request __error:(NSError**) __error;
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(RequestResultHandler*) requestMgr; 

@end
