//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "Staff.h"
#import "SessionType.h"
#import "ArrayOfProgram.h"
#import "Location.h"
#import "ScheduleItem.h"
#import "Helper.h"
#import "Availability.h"


@implementation Availability
    @synthesize ID;
    @synthesize Staff;
    @synthesize SessionType;
    @synthesize Programs;
    @synthesize StartDateTime;
    @synthesize EndDateTime;
    @synthesize BookableEndDateTime;
    @synthesize Location;

+ (Availability *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"ID"])
        {
            self.ID = [[Helper getNode:__node name:@"ID"] stringValue];
        }
        if([Helper hasValue:__node name:@"Staff"])
        {
            self.Staff = (Staff*)[__request createObject:[Helper getNode:__node name:@"Staff"] type:[Staff class]];
        }
        if([Helper hasValue:__node name:@"SessionType"])
        {
            self.SessionType = (SessionType*)[__request createObject:[Helper getNode:__node name:@"SessionType"] type:[SessionType class]];
        }
        if([Helper hasValue:__node name:@"Programs"])
        {
            self.Programs = (ArrayOfProgram*)[__request createObject:[Helper getNode:__node name:@"Programs"] type:[ArrayOfProgram class]];
        }
        if([Helper hasValue:__node name:@"StartDateTime"])
        {
            self.StartDateTime = [[Helper getNode:__node name:@"StartDateTime"] stringValue];
        }
        if([Helper hasValue:__node name:@"EndDateTime"])
        {
            self.EndDateTime = [[Helper getNode:__node name:@"EndDateTime"] stringValue];
        }
        if([Helper hasValue:__node name:@"BookableEndDateTime"])
        {
            self.BookableEndDateTime = [[Helper getNode:__node name:@"BookableEndDateTime"] stringValue];
        }
        if([Helper hasValue:__node name:@"Location"])
        {
            self.Location = (Location*)[__request createObject:[Helper getNode:__node name:@"Location"] type:[Location class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __IDItemElement=[__request writeElement:ID type:[NSString class] name:@"ID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IDItemElement!=nil)
        {
            [__IDItemElement setStringValue:self.ID];
        }
             
        DDXMLElement* __StaffItemElement=[__request writeElement:Staff type:[Staff class] name:@"Staff" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StaffItemElement!=nil)
        {
            [self.Staff serialize:__StaffItemElement __request: __request];
        }
             
        DDXMLElement* __SessionTypeItemElement=[__request writeElement:SessionType type:[SessionType class] name:@"SessionType" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__SessionTypeItemElement!=nil)
        {
            [self.SessionType serialize:__SessionTypeItemElement __request: __request];
        }
             
        DDXMLElement* __ProgramsItemElement=[__request writeElement:Programs type:[ArrayOfProgram class] name:@"Programs" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ProgramsItemElement!=nil)
        {
            [self.Programs serialize:__ProgramsItemElement __request: __request];
        }
             
        DDXMLElement* __StartDateTimeItemElement=[__request writeElement:StartDateTime type:[NSString class] name:@"StartDateTime" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StartDateTimeItemElement!=nil)
        {
            [__StartDateTimeItemElement setStringValue:self.StartDateTime];
        }
             
        DDXMLElement* __EndDateTimeItemElement=[__request writeElement:EndDateTime type:[NSString class] name:@"EndDateTime" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EndDateTimeItemElement!=nil)
        {
            [__EndDateTimeItemElement setStringValue:self.EndDateTime];
        }
             
        DDXMLElement* __BookableEndDateTimeItemElement=[__request writeElement:BookableEndDateTime type:[NSString class] name:@"BookableEndDateTime" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__BookableEndDateTimeItemElement!=nil)
        {
            [__BookableEndDateTimeItemElement setStringValue:self.BookableEndDateTime];
        }
             
        DDXMLElement* __LocationItemElement=[__request writeElement:Location type:[Location class] name:@"Location" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LocationItemElement!=nil)
        {
            [self.Location serialize:__LocationItemElement __request: __request];
        }


}
@end
