//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "Program.h"
#import "MBObject.h"
#import "Helper.h"
#import "ClientService.h"


@implementation ClientService
    @synthesize Current;
    @synthesize Count;
    @synthesize Remaining;
    @synthesize Action;
    @synthesize ID;
    @synthesize Name;
    @synthesize PaymentDate;
    @synthesize ActiveDate;
    @synthesize ExpirationDate;
    @synthesize Program;

+ (ClientService *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"Current"])
        {
            self.Current = [[Helper getNode:__node name:@"Current"] stringValue];
        }
        if([Helper hasValue:__node name:@"Count"])
        {
            self.Count = [[Helper getNode:__node name:@"Count"] stringValue];
        }
        if([Helper hasValue:__node name:@"Remaining"])
        {
            self.Remaining = [[Helper getNode:__node name:@"Remaining"] stringValue];
        }
        if([Helper hasValue:__node name:@"Action"])
        {
            self.Action = [[Helper getNode:__node name:@"Action"] stringValue];
        }
        if([Helper hasValue:__node name:@"ID"])
        {
            self.ID = [[Helper getNode:__node name:@"ID"] stringValue];
        }
        if([Helper hasValue:__node name:@"Name"])
        {
            self.Name = [[Helper getNode:__node name:@"Name"] stringValue];
        }
        if([Helper hasValue:__node name:@"PaymentDate"])
        {
            self.PaymentDate = [[Helper getNode:__node name:@"PaymentDate"] stringValue];
        }
        if([Helper hasValue:__node name:@"ActiveDate"])
        {
            self.ActiveDate = [[Helper getNode:__node name:@"ActiveDate"] stringValue];
        }
        if([Helper hasValue:__node name:@"ExpirationDate"])
        {
            self.ExpirationDate = [[Helper getNode:__node name:@"ExpirationDate"] stringValue];
        }
        if([Helper hasValue:__node name:@"Program"])
        {
            self.Program = (Program*)[__request createObject:[Helper getNode:__node name:@"Program"] type:[Program class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __CurrentItemElement=[__request writeElement:Current type:[NSString class] name:@"Current" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CurrentItemElement!=nil)
        {
            [__CurrentItemElement setStringValue:self.Current];
        }
             
        DDXMLElement* __CountItemElement=[__request writeElement:Count type:[NSString class] name:@"Count" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CountItemElement!=nil)
        {
            [__CountItemElement setStringValue:self.Count];
        }
             
        DDXMLElement* __RemainingItemElement=[__request writeElement:Remaining type:[NSString class] name:@"Remaining" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__RemainingItemElement!=nil)
        {
            [__RemainingItemElement setStringValue:self.Remaining];
        }
             
        DDXMLElement* __ActionItemElement=[__request writeElement:Action type:[NSString class] name:@"Action" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ActionItemElement!=nil)
        {
            [__ActionItemElement setStringValue:self.Action];
        }
             
        DDXMLElement* __IDItemElement=[__request writeElement:ID type:[NSString class] name:@"ID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IDItemElement!=nil)
        {
            [__IDItemElement setStringValue:self.ID];
        }
             
        DDXMLElement* __NameItemElement=[__request writeElement:Name type:[NSString class] name:@"Name" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__NameItemElement!=nil)
        {
            [__NameItemElement setStringValue:self.Name];
        }
             
        DDXMLElement* __PaymentDateItemElement=[__request writeElement:PaymentDate type:[NSString class] name:@"PaymentDate" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PaymentDateItemElement!=nil)
        {
            [__PaymentDateItemElement setStringValue:self.PaymentDate];
        }
             
        DDXMLElement* __ActiveDateItemElement=[__request writeElement:ActiveDate type:[NSString class] name:@"ActiveDate" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ActiveDateItemElement!=nil)
        {
            [__ActiveDateItemElement setStringValue:self.ActiveDate];
        }
             
        DDXMLElement* __ExpirationDateItemElement=[__request writeElement:ExpirationDate type:[NSString class] name:@"ExpirationDate" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ExpirationDateItemElement!=nil)
        {
            [__ExpirationDateItemElement setStringValue:self.ExpirationDate];
        }
             
        DDXMLElement* __ProgramItemElement=[__request writeElement:Program type:[Program class] name:@"Program" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ProgramItemElement!=nil)
        {
            [self.Program serialize:__ProgramItemElement __request: __request];
        }


}
@end
