//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "RequestResultHandler.h"
#import "DDXML.h"



@interface ClientCreditCard : NSObject 


@property (retain,nonatomic,getter=getCardType) NSString* CardType;

@property (retain,nonatomic,getter=getLastFour) NSString* LastFour;

@property (retain,nonatomic,getter=getCardNumber) NSString* CardNumber;

@property (retain,nonatomic,getter=getCardHolder) NSString* CardHolder;

@property (retain,nonatomic,getter=getExpMonth) NSString* ExpMonth;

@property (retain,nonatomic,getter=getExpYear) NSString* ExpYear;

@property (retain,nonatomic,getter=getAddress) NSString* Address;

@property (retain,nonatomic,getter=getCity) NSString* City;

@property (retain,nonatomic,getter=getState) NSString* State;

@property (retain,nonatomic,getter=getPostalCode) NSString* PostalCode;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(ClientCreditCard*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end