//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "Helper.h"
#import "ClientCreditCard.h"


@implementation ClientCreditCard
    @synthesize CardType;
    @synthesize LastFour;
    @synthesize CardNumber;
    @synthesize CardHolder;
    @synthesize ExpMonth;
    @synthesize ExpYear;
    @synthesize Address;
    @synthesize City;
    @synthesize State;
    @synthesize PostalCode;

+ (ClientCreditCard *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"CardType"])
        {
            self.CardType = [[Helper getNode:__node name:@"CardType"] stringValue];
        }
        if([Helper hasValue:__node name:@"LastFour"])
        {
            self.LastFour = [[Helper getNode:__node name:@"LastFour"] stringValue];
        }
        if([Helper hasValue:__node name:@"CardNumber"])
        {
            self.CardNumber = [[Helper getNode:__node name:@"CardNumber"] stringValue];
        }
        if([Helper hasValue:__node name:@"CardHolder"])
        {
            self.CardHolder = [[Helper getNode:__node name:@"CardHolder"] stringValue];
        }
        if([Helper hasValue:__node name:@"ExpMonth"])
        {
            self.ExpMonth = [[Helper getNode:__node name:@"ExpMonth"] stringValue];
        }
        if([Helper hasValue:__node name:@"ExpYear"])
        {
            self.ExpYear = [[Helper getNode:__node name:@"ExpYear"] stringValue];
        }
        if([Helper hasValue:__node name:@"Address"])
        {
            self.Address = [[Helper getNode:__node name:@"Address"] stringValue];
        }
        if([Helper hasValue:__node name:@"City"])
        {
            self.City = [[Helper getNode:__node name:@"City"] stringValue];
        }
        if([Helper hasValue:__node name:@"State"])
        {
            self.State = [[Helper getNode:__node name:@"State"] stringValue];
        }
        if([Helper hasValue:__node name:@"PostalCode"])
        {
            self.PostalCode = [[Helper getNode:__node name:@"PostalCode"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
        DDXMLElement* __CardTypeItemElement=[__request writeElement:CardType type:[NSString class] name:@"CardType" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CardTypeItemElement!=nil)
        {
            [__CardTypeItemElement setStringValue:self.CardType];
        }
             
        DDXMLElement* __LastFourItemElement=[__request writeElement:LastFour type:[NSString class] name:@"LastFour" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LastFourItemElement!=nil)
        {
            [__LastFourItemElement setStringValue:self.LastFour];
        }
             
        DDXMLElement* __CardNumberItemElement=[__request writeElement:CardNumber type:[NSString class] name:@"CardNumber" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CardNumberItemElement!=nil)
        {
            [__CardNumberItemElement setStringValue:self.CardNumber];
        }
             
        DDXMLElement* __CardHolderItemElement=[__request writeElement:CardHolder type:[NSString class] name:@"CardHolder" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CardHolderItemElement!=nil)
        {
            [__CardHolderItemElement setStringValue:self.CardHolder];
        }
             
        DDXMLElement* __ExpMonthItemElement=[__request writeElement:ExpMonth type:[NSString class] name:@"ExpMonth" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ExpMonthItemElement!=nil)
        {
            [__ExpMonthItemElement setStringValue:self.ExpMonth];
        }
             
        DDXMLElement* __ExpYearItemElement=[__request writeElement:ExpYear type:[NSString class] name:@"ExpYear" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ExpYearItemElement!=nil)
        {
            [__ExpYearItemElement setStringValue:self.ExpYear];
        }
             
        DDXMLElement* __AddressItemElement=[__request writeElement:Address type:[NSString class] name:@"Address" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AddressItemElement!=nil)
        {
            [__AddressItemElement setStringValue:self.Address];
        }
             
        DDXMLElement* __CityItemElement=[__request writeElement:City type:[NSString class] name:@"City" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CityItemElement!=nil)
        {
            [__CityItemElement setStringValue:self.City];
        }
             
        DDXMLElement* __StateItemElement=[__request writeElement:State type:[NSString class] name:@"State" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StateItemElement!=nil)
        {
            [__StateItemElement setStringValue:self.State];
        }
             
        DDXMLElement* __PostalCodeItemElement=[__request writeElement:PostalCode type:[NSString class] name:@"PostalCode" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PostalCodeItemElement!=nil)
        {
            [__PostalCodeItemElement setStringValue:self.PostalCode];
        }


}
@end
