//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "ArrayOfClientIndex.h"
#import "ClientCreditCard.h"
#import "ArrayOfClientRelationship.h"
#import "ArrayOfRep.h"
#import "ArrayOfCustomClientField.h"
#import "Location.h"
#import "MBObject.h"
#import "Helper.h"
#import "Client.h"


@implementation Client
    @synthesize NewID;
    @synthesize AccountBalance;
    @synthesize ClientIndexes;
    @synthesize Username;
    @synthesize Password;
    @synthesize Notes;
    @synthesize ClientCreditCard;
    @synthesize LastFormulaNotes;
    @synthesize AppointmentGenderPreference;
    @synthesize Gender;
    @synthesize IsCompany;
    @synthesize Inactive;
    @synthesize ClientRelationships;
    @synthesize Reps;
    @synthesize CustomClientFields;
    @synthesize LiabilityRelease;
    @synthesize EmergencyContactInfoName;
    @synthesize EmergencyContactInfoRelationship;
    @synthesize EmergencyContactInfoPhone;
    @synthesize EmergencyContactInfoEmail;
    @synthesize Action;
    @synthesize ID;
    @synthesize FirstName;
    @synthesize MiddleName;
    @synthesize LastName;
    @synthesize Email;
    @synthesize EmailOptIn;
    @synthesize AddressLine1;
    @synthesize AddressLine2;
    @synthesize City;
    @synthesize State;
    @synthesize PostalCode;
    @synthesize Country;
    @synthesize MobilePhone;
    @synthesize HomePhone;
    @synthesize WorkPhone;
    @synthesize WorkExtension;
    @synthesize BirthDate;
    @synthesize FirstAppointmentDate;
    @synthesize ReferredBy;
    @synthesize HomeLocation;
    @synthesize YellowAlert;
    @synthesize RedAlert;
    @synthesize PhotoURL;
    @synthesize IsProspect;

+ (Client *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"NewID"])
        {
            self.NewID = [[Helper getNode:__node name:@"NewID"] stringValue];
        }
        if([Helper hasValue:__node name:@"AccountBalance"])
        {
            self.AccountBalance = [[Helper getNode:__node name:@"AccountBalance"] stringValue];
        }
        if([Helper hasValue:__node name:@"ClientIndexes"])
        {
            self.ClientIndexes = (ArrayOfClientIndex*)[__request createObject:[Helper getNode:__node name:@"ClientIndexes"] type:[ArrayOfClientIndex class]];
        }
        if([Helper hasValue:__node name:@"Username"])
        {
            self.Username = [[Helper getNode:__node name:@"Username"] stringValue];
        }
        if([Helper hasValue:__node name:@"Password"])
        {
            self.Password = [[Helper getNode:__node name:@"Password"] stringValue];
        }
        if([Helper hasValue:__node name:@"Notes"])
        {
            self.Notes = [[Helper getNode:__node name:@"Notes"] stringValue];
        }
        if([Helper hasValue:__node name:@"ClientCreditCard"])
        {
            self.ClientCreditCard = (ClientCreditCard*)[__request createObject:[Helper getNode:__node name:@"ClientCreditCard"] type:[ClientCreditCard class]];
        }
        if([Helper hasValue:__node name:@"LastFormulaNotes"])
        {
            self.LastFormulaNotes = [[Helper getNode:__node name:@"LastFormulaNotes"] stringValue];
        }
        if([Helper hasValue:__node name:@"AppointmentGenderPreference"])
        {
            self.AppointmentGenderPreference = [[Helper getNode:__node name:@"AppointmentGenderPreference"] stringValue];
        }
        if([Helper hasValue:__node name:@"Gender"])
        {
            self.Gender = [[Helper getNode:__node name:@"Gender"] stringValue];
        }
        if([Helper hasValue:__node name:@"IsCompany"])
        {
            self.IsCompany = [[Helper getNode:__node name:@"IsCompany"] stringValue];
        }
        if([Helper hasValue:__node name:@"Inactive"])
        {
            self.Inactive = [[Helper getNode:__node name:@"Inactive"] stringValue];
        }
        if([Helper hasValue:__node name:@"ClientRelationships"])
        {
            self.ClientRelationships = (ArrayOfClientRelationship*)[__request createObject:[Helper getNode:__node name:@"ClientRelationships"] type:[ArrayOfClientRelationship class]];
        }
        if([Helper hasValue:__node name:@"Reps"])
        {
            self.Reps = (ArrayOfRep*)[__request createObject:[Helper getNode:__node name:@"Reps"] type:[ArrayOfRep class]];
        }
        if([Helper hasValue:__node name:@"CustomClientFields"])
        {
            self.CustomClientFields = (ArrayOfCustomClientField*)[__request createObject:[Helper getNode:__node name:@"CustomClientFields"] type:[ArrayOfCustomClientField class]];
        }
        if([Helper hasValue:__node name:@"LiabilityRelease"])
        {
            self.LiabilityRelease = [[Helper getNode:__node name:@"LiabilityRelease"] stringValue];
        }
        if([Helper hasValue:__node name:@"EmergencyContactInfoName"])
        {
            self.EmergencyContactInfoName = [[Helper getNode:__node name:@"EmergencyContactInfoName"] stringValue];
        }
        if([Helper hasValue:__node name:@"EmergencyContactInfoRelationship"])
        {
            self.EmergencyContactInfoRelationship = [[Helper getNode:__node name:@"EmergencyContactInfoRelationship"] stringValue];
        }
        if([Helper hasValue:__node name:@"EmergencyContactInfoPhone"])
        {
            self.EmergencyContactInfoPhone = [[Helper getNode:__node name:@"EmergencyContactInfoPhone"] stringValue];
        }
        if([Helper hasValue:__node name:@"EmergencyContactInfoEmail"])
        {
            self.EmergencyContactInfoEmail = [[Helper getNode:__node name:@"EmergencyContactInfoEmail"] stringValue];
        }
        if([Helper hasValue:__node name:@"Action"])
        {
            self.Action = [[Helper getNode:__node name:@"Action"] stringValue];
        }
        if([Helper hasValue:__node name:@"ID"])
        {
            self.ID = [[Helper getNode:__node name:@"ID"] stringValue];
        }
        if([Helper hasValue:__node name:@"FirstName"])
        {
            self.FirstName = [[Helper getNode:__node name:@"FirstName"] stringValue];
        }
        if([Helper hasValue:__node name:@"MiddleName"])
        {
            self.MiddleName = [[Helper getNode:__node name:@"MiddleName"] stringValue];
        }
        if([Helper hasValue:__node name:@"LastName"])
        {
            self.LastName = [[Helper getNode:__node name:@"LastName"] stringValue];
        }
        if([Helper hasValue:__node name:@"Email"])
        {
            self.Email = [[Helper getNode:__node name:@"Email"] stringValue];
        }
        if([Helper hasValue:__node name:@"EmailOptIn"])
        {
            self.EmailOptIn = [[Helper getNode:__node name:@"EmailOptIn"] stringValue];
        }
        if([Helper hasValue:__node name:@"AddressLine1"])
        {
            self.AddressLine1 = [[Helper getNode:__node name:@"AddressLine1"] stringValue];
        }
        if([Helper hasValue:__node name:@"AddressLine2"])
        {
            self.AddressLine2 = [[Helper getNode:__node name:@"AddressLine2"] stringValue];
        }
        if([Helper hasValue:__node name:@"City"])
        {
            self.City = [[Helper getNode:__node name:@"City"] stringValue];
        }
        if([Helper hasValue:__node name:@"State"])
        {
            self.State = [[Helper getNode:__node name:@"State"] stringValue];
        }
        if([Helper hasValue:__node name:@"PostalCode"])
        {
            self.PostalCode = [[Helper getNode:__node name:@"PostalCode"] stringValue];
        }
        if([Helper hasValue:__node name:@"Country"])
        {
            self.Country = [[Helper getNode:__node name:@"Country"] stringValue];
        }
        if([Helper hasValue:__node name:@"MobilePhone"])
        {
            self.MobilePhone = [[Helper getNode:__node name:@"MobilePhone"] stringValue];
        }
        if([Helper hasValue:__node name:@"HomePhone"])
        {
            self.HomePhone = [[Helper getNode:__node name:@"HomePhone"] stringValue];
        }
        if([Helper hasValue:__node name:@"WorkPhone"])
        {
            self.WorkPhone = [[Helper getNode:__node name:@"WorkPhone"] stringValue];
        }
        if([Helper hasValue:__node name:@"WorkExtension"])
        {
            self.WorkExtension = [[Helper getNode:__node name:@"WorkExtension"] stringValue];
        }
        if([Helper hasValue:__node name:@"BirthDate"])
        {
            self.BirthDate = [[Helper getNode:__node name:@"BirthDate"] stringValue];
        }
        if([Helper hasValue:__node name:@"FirstAppointmentDate"])
        {
            self.FirstAppointmentDate = [[Helper getNode:__node name:@"FirstAppointmentDate"] stringValue];
        }
        if([Helper hasValue:__node name:@"ReferredBy"])
        {
            self.ReferredBy = [[Helper getNode:__node name:@"ReferredBy"] stringValue];
        }
        if([Helper hasValue:__node name:@"HomeLocation"])
        {
            self.HomeLocation = (Location*)[__request createObject:[Helper getNode:__node name:@"HomeLocation"] type:[Location class]];
        }
        if([Helper hasValue:__node name:@"YellowAlert"])
        {
            self.YellowAlert = [[Helper getNode:__node name:@"YellowAlert"] stringValue];
        }
        if([Helper hasValue:__node name:@"RedAlert"])
        {
            self.RedAlert = [[Helper getNode:__node name:@"RedAlert"] stringValue];
        }
        if([Helper hasValue:__node name:@"PhotoURL"])
        {
            self.PhotoURL = [[Helper getNode:__node name:@"PhotoURL"] stringValue];
        }
        if([Helper hasValue:__node name:@"IsProspect"])
        {
            self.IsProspect = [[Helper getNode:__node name:@"IsProspect"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __NewIDItemElement=[__request writeElement:NewID type:[NSString class] name:@"NewID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__NewIDItemElement!=nil)
        {
            [__NewIDItemElement setStringValue:self.NewID];
        }
             
        DDXMLElement* __AccountBalanceItemElement=[__request writeElement:AccountBalance type:[NSString class] name:@"AccountBalance" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AccountBalanceItemElement!=nil)
        {
            [__AccountBalanceItemElement setStringValue:self.AccountBalance];
        }
             
        DDXMLElement* __ClientIndexesItemElement=[__request writeElement:ClientIndexes type:[ArrayOfClientIndex class] name:@"ClientIndexes" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ClientIndexesItemElement!=nil)
        {
            [self.ClientIndexes serialize:__ClientIndexesItemElement __request: __request];
        }
             
        DDXMLElement* __UsernameItemElement=[__request writeElement:Username type:[NSString class] name:@"Username" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__UsernameItemElement!=nil)
        {
            [__UsernameItemElement setStringValue:self.Username];
        }
             
        DDXMLElement* __PasswordItemElement=[__request writeElement:Password type:[NSString class] name:@"Password" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PasswordItemElement!=nil)
        {
            [__PasswordItemElement setStringValue:self.Password];
        }
             
        DDXMLElement* __NotesItemElement=[__request writeElement:Notes type:[NSString class] name:@"Notes" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__NotesItemElement!=nil)
        {
            [__NotesItemElement setStringValue:self.Notes];
        }
             
        DDXMLElement* __ClientCreditCardItemElement=[__request writeElement:ClientCreditCard type:[ClientCreditCard class] name:@"ClientCreditCard" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ClientCreditCardItemElement!=nil)
        {
            [self.ClientCreditCard serialize:__ClientCreditCardItemElement __request: __request];
        }
             
        DDXMLElement* __LastFormulaNotesItemElement=[__request writeElement:LastFormulaNotes type:[NSString class] name:@"LastFormulaNotes" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LastFormulaNotesItemElement!=nil)
        {
            [__LastFormulaNotesItemElement setStringValue:self.LastFormulaNotes];
        }
             
        DDXMLElement* __AppointmentGenderPreferenceItemElement=[__request writeElement:AppointmentGenderPreference type:[NSString class] name:@"AppointmentGenderPreference" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AppointmentGenderPreferenceItemElement!=nil)
        {
            [__AppointmentGenderPreferenceItemElement setStringValue:self.AppointmentGenderPreference];
        }
             
        DDXMLElement* __GenderItemElement=[__request writeElement:Gender type:[NSString class] name:@"Gender" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__GenderItemElement!=nil)
        {
            [__GenderItemElement setStringValue:self.Gender];
        }
             
        DDXMLElement* __IsCompanyItemElement=[__request writeElement:IsCompany type:[NSString class] name:@"IsCompany" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IsCompanyItemElement!=nil)
        {
            [__IsCompanyItemElement setStringValue:self.IsCompany];
        }
             
        DDXMLElement* __InactiveItemElement=[__request writeElement:Inactive type:[NSString class] name:@"Inactive" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__InactiveItemElement!=nil)
        {
            [__InactiveItemElement setStringValue:self.Inactive];
        }
             
        DDXMLElement* __ClientRelationshipsItemElement=[__request writeElement:ClientRelationships type:[ArrayOfClientRelationship class] name:@"ClientRelationships" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ClientRelationshipsItemElement!=nil)
        {
            [self.ClientRelationships serialize:__ClientRelationshipsItemElement __request: __request];
        }
             
        DDXMLElement* __RepsItemElement=[__request writeElement:Reps type:[ArrayOfRep class] name:@"Reps" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__RepsItemElement!=nil)
        {
            [self.Reps serialize:__RepsItemElement __request: __request];
        }
             
        DDXMLElement* __CustomClientFieldsItemElement=[__request writeElement:CustomClientFields type:[ArrayOfCustomClientField class] name:@"CustomClientFields" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CustomClientFieldsItemElement!=nil)
        {
            [self.CustomClientFields serialize:__CustomClientFieldsItemElement __request: __request];
        }
             
        DDXMLElement* __LiabilityReleaseItemElement=[__request writeElement:LiabilityRelease type:[NSString class] name:@"LiabilityRelease" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LiabilityReleaseItemElement!=nil)
        {
            [__LiabilityReleaseItemElement setStringValue:self.LiabilityRelease];
        }
             
        DDXMLElement* __EmergencyContactInfoNameItemElement=[__request writeElement:EmergencyContactInfoName type:[NSString class] name:@"EmergencyContactInfoName" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EmergencyContactInfoNameItemElement!=nil)
        {
            [__EmergencyContactInfoNameItemElement setStringValue:self.EmergencyContactInfoName];
        }
             
        DDXMLElement* __EmergencyContactInfoRelationshipItemElement=[__request writeElement:EmergencyContactInfoRelationship type:[NSString class] name:@"EmergencyContactInfoRelationship" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EmergencyContactInfoRelationshipItemElement!=nil)
        {
            [__EmergencyContactInfoRelationshipItemElement setStringValue:self.EmergencyContactInfoRelationship];
        }
             
        DDXMLElement* __EmergencyContactInfoPhoneItemElement=[__request writeElement:EmergencyContactInfoPhone type:[NSString class] name:@"EmergencyContactInfoPhone" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EmergencyContactInfoPhoneItemElement!=nil)
        {
            [__EmergencyContactInfoPhoneItemElement setStringValue:self.EmergencyContactInfoPhone];
        }
             
        DDXMLElement* __EmergencyContactInfoEmailItemElement=[__request writeElement:EmergencyContactInfoEmail type:[NSString class] name:@"EmergencyContactInfoEmail" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EmergencyContactInfoEmailItemElement!=nil)
        {
            [__EmergencyContactInfoEmailItemElement setStringValue:self.EmergencyContactInfoEmail];
        }
             
        DDXMLElement* __ActionItemElement=[__request writeElement:Action type:[NSString class] name:@"Action" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ActionItemElement!=nil)
        {
            [__ActionItemElement setStringValue:self.Action];
        }
             
        DDXMLElement* __IDItemElement=[__request writeElement:ID type:[NSString class] name:@"ID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IDItemElement!=nil)
        {
            [__IDItemElement setStringValue:self.ID];
        }
             
        DDXMLElement* __FirstNameItemElement=[__request writeElement:FirstName type:[NSString class] name:@"FirstName" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__FirstNameItemElement!=nil)
        {
            [__FirstNameItemElement setStringValue:self.FirstName];
        }
             
        DDXMLElement* __MiddleNameItemElement=[__request writeElement:MiddleName type:[NSString class] name:@"MiddleName" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__MiddleNameItemElement!=nil)
        {
            [__MiddleNameItemElement setStringValue:self.MiddleName];
        }
             
        DDXMLElement* __LastNameItemElement=[__request writeElement:LastName type:[NSString class] name:@"LastName" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LastNameItemElement!=nil)
        {
            [__LastNameItemElement setStringValue:self.LastName];
        }
             
        DDXMLElement* __EmailItemElement=[__request writeElement:Email type:[NSString class] name:@"Email" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EmailItemElement!=nil)
        {
            [__EmailItemElement setStringValue:self.Email];
        }
             
        DDXMLElement* __EmailOptInItemElement=[__request writeElement:EmailOptIn type:[NSString class] name:@"EmailOptIn" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EmailOptInItemElement!=nil)
        {
            [__EmailOptInItemElement setStringValue:self.EmailOptIn];
        }
             
        DDXMLElement* __AddressLine1ItemElement=[__request writeElement:AddressLine1 type:[NSString class] name:@"AddressLine1" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AddressLine1ItemElement!=nil)
        {
            [__AddressLine1ItemElement setStringValue:self.AddressLine1];
        }
             
        DDXMLElement* __AddressLine2ItemElement=[__request writeElement:AddressLine2 type:[NSString class] name:@"AddressLine2" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AddressLine2ItemElement!=nil)
        {
            [__AddressLine2ItemElement setStringValue:self.AddressLine2];
        }
             
        DDXMLElement* __CityItemElement=[__request writeElement:City type:[NSString class] name:@"City" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CityItemElement!=nil)
        {
            [__CityItemElement setStringValue:self.City];
        }
             
        DDXMLElement* __StateItemElement=[__request writeElement:State type:[NSString class] name:@"State" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StateItemElement!=nil)
        {
            [__StateItemElement setStringValue:self.State];
        }
             
        DDXMLElement* __PostalCodeItemElement=[__request writeElement:PostalCode type:[NSString class] name:@"PostalCode" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PostalCodeItemElement!=nil)
        {
            [__PostalCodeItemElement setStringValue:self.PostalCode];
        }
             
        DDXMLElement* __CountryItemElement=[__request writeElement:Country type:[NSString class] name:@"Country" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CountryItemElement!=nil)
        {
            [__CountryItemElement setStringValue:self.Country];
        }
             
        DDXMLElement* __MobilePhoneItemElement=[__request writeElement:MobilePhone type:[NSString class] name:@"MobilePhone" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__MobilePhoneItemElement!=nil)
        {
            [__MobilePhoneItemElement setStringValue:self.MobilePhone];
        }
             
        DDXMLElement* __HomePhoneItemElement=[__request writeElement:HomePhone type:[NSString class] name:@"HomePhone" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__HomePhoneItemElement!=nil)
        {
            [__HomePhoneItemElement setStringValue:self.HomePhone];
        }
             
        DDXMLElement* __WorkPhoneItemElement=[__request writeElement:WorkPhone type:[NSString class] name:@"WorkPhone" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__WorkPhoneItemElement!=nil)
        {
            [__WorkPhoneItemElement setStringValue:self.WorkPhone];
        }
             
        DDXMLElement* __WorkExtensionItemElement=[__request writeElement:WorkExtension type:[NSString class] name:@"WorkExtension" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__WorkExtensionItemElement!=nil)
        {
            [__WorkExtensionItemElement setStringValue:self.WorkExtension];
        }
             
        DDXMLElement* __BirthDateItemElement=[__request writeElement:BirthDate type:[NSString class] name:@"BirthDate" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__BirthDateItemElement!=nil)
        {
            [__BirthDateItemElement setStringValue:self.BirthDate];
        }
             
        DDXMLElement* __FirstAppointmentDateItemElement=[__request writeElement:FirstAppointmentDate type:[NSString class] name:@"FirstAppointmentDate" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__FirstAppointmentDateItemElement!=nil)
        {
            [__FirstAppointmentDateItemElement setStringValue:self.FirstAppointmentDate];
        }
             
        DDXMLElement* __ReferredByItemElement=[__request writeElement:ReferredBy type:[NSString class] name:@"ReferredBy" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ReferredByItemElement!=nil)
        {
            [__ReferredByItemElement setStringValue:self.ReferredBy];
        }
             
        DDXMLElement* __HomeLocationItemElement=[__request writeElement:HomeLocation type:[Location class] name:@"HomeLocation" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__HomeLocationItemElement!=nil)
        {
            [self.HomeLocation serialize:__HomeLocationItemElement __request: __request];
        }
             
        DDXMLElement* __YellowAlertItemElement=[__request writeElement:YellowAlert type:[NSString class] name:@"YellowAlert" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__YellowAlertItemElement!=nil)
        {
            [__YellowAlertItemElement setStringValue:self.YellowAlert];
        }
             
        DDXMLElement* __RedAlertItemElement=[__request writeElement:RedAlert type:[NSString class] name:@"RedAlert" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__RedAlertItemElement!=nil)
        {
            [__RedAlertItemElement setStringValue:self.RedAlert];
        }
             
        DDXMLElement* __PhotoURLItemElement=[__request writeElement:PhotoURL type:[NSString class] name:@"PhotoURL" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PhotoURLItemElement!=nil)
        {
            [__PhotoURLItemElement setStringValue:self.PhotoURL];
        }
             
        DDXMLElement* __IsProspectItemElement=[__request writeElement:IsProspect type:[NSString class] name:@"IsProspect" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IsProspectItemElement!=nil)
        {
            [__IsProspectItemElement setStringValue:self.IsProspect];
        }


}
@end
