//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class Client;
@class Relationship;
#import "MBObject.h"
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface ClientRelationship : MBObject 


@property (retain,nonatomic,getter=getRelatedClient) Client* RelatedClient;

@property (retain,nonatomic,getter=getRelationship) Relationship* Relationship;

@property (retain,nonatomic,getter=getRelationshipName) NSString* RelationshipName;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(ClientRelationship*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end