//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "Client.h"
#import "Relationship.h"
#import "MBObject.h"
#import "Helper.h"
#import "ClientRelationship.h"


@implementation ClientRelationship
    @synthesize RelatedClient;
    @synthesize Relationship;
    @synthesize RelationshipName;

+ (ClientRelationship *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"RelatedClient"])
        {
            self.RelatedClient = (Client*)[__request createObject:[Helper getNode:__node name:@"RelatedClient"] type:[Client class]];
        }
        if([Helper hasValue:__node name:@"Relationship"])
        {
            self.Relationship = (Relationship*)[__request createObject:[Helper getNode:__node name:@"Relationship"] type:[Relationship class]];
        }
        if([Helper hasValue:__node name:@"RelationshipName"])
        {
            self.RelationshipName = [[Helper getNode:__node name:@"RelationshipName"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __RelatedClientItemElement=[__request writeElement:RelatedClient type:[Client class] name:@"RelatedClient" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__RelatedClientItemElement!=nil)
        {
            [self.RelatedClient serialize:__RelatedClientItemElement __request: __request];
        }
             
        DDXMLElement* __RelationshipItemElement=[__request writeElement:Relationship type:[Relationship class] name:@"Relationship" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__RelationshipItemElement!=nil)
        {
            [self.Relationship serialize:__RelationshipItemElement __request: __request];
        }
             
        DDXMLElement* __RelationshipNameItemElement=[__request writeElement:RelationshipName type:[NSString class] name:@"RelationshipName" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__RelationshipNameItemElement!=nil)
        {
            [__RelationshipNameItemElement setStringValue:self.RelationshipName];
        }


}
@end
