//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class ArrayOfClientIndex;
@class ClientCreditCard;
@class ArrayOfClientRelationship;
@class ArrayOfRep;
@class ArrayOfCustomClientField;
@class Location;
#import "MBObject.h"
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface Client : MBObject 


@property (retain,nonatomic,getter=getNewID) NSString* NewID;

@property (retain,nonatomic,getter=getAccountBalance) NSString* AccountBalance;

@property (retain,nonatomic,getter=getClientIndexes) ArrayOfClientIndex* ClientIndexes;

@property (retain,nonatomic,getter=getUsername) NSString* Username;

@property (retain,nonatomic,getter=getPassword) NSString* Password;

@property (retain,nonatomic,getter=getNotes) NSString* Notes;

@property (retain,nonatomic,getter=getClientCreditCard) ClientCreditCard* ClientCreditCard;

@property (retain,nonatomic,getter=getLastFormulaNotes) NSString* LastFormulaNotes;

@property (retain,nonatomic,getter=getAppointmentGenderPreference) NSString* AppointmentGenderPreference;

@property (retain,nonatomic,getter=getGender) NSString* Gender;

@property (retain,nonatomic,getter=getIsCompany) NSString* IsCompany;

@property (retain,nonatomic,getter=getInactive) NSString* Inactive;

@property (retain,nonatomic,getter=getClientRelationships) ArrayOfClientRelationship* ClientRelationships;

@property (retain,nonatomic,getter=getReps) ArrayOfRep* Reps;

@property (retain,nonatomic,getter=getCustomClientFields) ArrayOfCustomClientField* CustomClientFields;

@property (retain,nonatomic,getter=getLiabilityRelease) NSString* LiabilityRelease;

@property (retain,nonatomic,getter=getEmergencyContactInfoName) NSString* EmergencyContactInfoName;

@property (retain,nonatomic,getter=getEmergencyContactInfoRelationship) NSString* EmergencyContactInfoRelationship;

@property (retain,nonatomic,getter=getEmergencyContactInfoPhone) NSString* EmergencyContactInfoPhone;

@property (retain,nonatomic,getter=getEmergencyContactInfoEmail) NSString* EmergencyContactInfoEmail;

@property (retain,nonatomic,getter=getAction) NSString* Action;

@property (retain,nonatomic,getter=getID) NSString* ID;

@property (retain,nonatomic,getter=getFirstName) NSString* FirstName;

@property (retain,nonatomic,getter=getMiddleName) NSString* MiddleName;

@property (retain,nonatomic,getter=getLastName) NSString* LastName;

@property (retain,nonatomic,getter=getEmail) NSString* Email;

@property (retain,nonatomic,getter=getEmailOptIn) NSString* EmailOptIn;

@property (retain,nonatomic,getter=getAddressLine1) NSString* AddressLine1;

@property (retain,nonatomic,getter=getAddressLine2) NSString* AddressLine2;

@property (retain,nonatomic,getter=getCity) NSString* City;

@property (retain,nonatomic,getter=getState) NSString* State;

@property (retain,nonatomic,getter=getPostalCode) NSString* PostalCode;

@property (retain,nonatomic,getter=getCountry) NSString* Country;

@property (retain,nonatomic,getter=getMobilePhone) NSString* MobilePhone;

@property (retain,nonatomic,getter=getHomePhone) NSString* HomePhone;

@property (retain,nonatomic,getter=getWorkPhone) NSString* WorkPhone;

@property (retain,nonatomic,getter=getWorkExtension) NSString* WorkExtension;

@property (retain,nonatomic,getter=getBirthDate) NSString* BirthDate;

@property (retain,nonatomic,getter=getFirstAppointmentDate) NSString* FirstAppointmentDate;

@property (retain,nonatomic,getter=getReferredBy) NSString* ReferredBy;

@property (retain,nonatomic,getter=getHomeLocation) Location* HomeLocation;

@property (retain,nonatomic,getter=getYellowAlert) NSString* YellowAlert;

@property (retain,nonatomic,getter=getRedAlert) NSString* RedAlert;

@property (retain,nonatomic,getter=getPhotoURL) NSString* PhotoURL;

@property (retain,nonatomic,getter=getIsProspect) NSString* IsProspect;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(Client*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end