//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "RequestResultHandler.h"
#import "DDXML.h"



@interface CustomClientField : NSObject 


@property (retain,nonatomic,getter=getID) NSString* ID;

@property (retain,nonatomic,getter=getDataType) NSString* DataType;

@property (retain,nonatomic,getter=getName) NSString* Name;

@property (retain,nonatomic,getter=getValue) NSString* Value;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(CustomClientField*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end