//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "ArrayOfDateTime.h"
#import "MBResult.h"
#import "Helper.h"
#import "GetActiveSessionTimesResult.h"


@implementation GetActiveSessionTimesResult
    @synthesize Times;

+ (GetActiveSessionTimesResult *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"Times"])
        {
            self.Times = (ArrayOfDateTime*)[__request createObject:[Helper getNode:__node name:@"Times"] type:[ArrayOfDateTime class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __TimesItemElement=[__request writeElement:Times type:[ArrayOfDateTime class] name:@"Times" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__TimesItemElement!=nil)
        {
            [self.Times serialize:__TimesItemElement __request: __request];
        }


}
@end
