//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "ArrayOfLong.h"
#import "StaffCredentials.h"
#import "ArrayOfStaffFilter.h"
#import "MBRequest.h"
#import "Helper.h"
#import "GetStaffRequest.h"


@implementation GetStaffRequest
    @synthesize StaffIDs;
    @synthesize StaffCredentials;
    @synthesize Filters;
    @synthesize SessionTypeID;
    @synthesize StartDateTime;
    @synthesize LocationID;

+ (GetStaffRequest *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"StaffIDs"])
        {
            self.StaffIDs = (ArrayOfLong*)[__request createObject:[Helper getNode:__node name:@"StaffIDs"] type:[ArrayOfLong class]];
        }
        if([Helper hasValue:__node name:@"StaffCredentials"])
        {
            self.StaffCredentials = (StaffCredentials*)[__request createObject:[Helper getNode:__node name:@"StaffCredentials"] type:[StaffCredentials class]];
        }
        if([Helper hasValue:__node name:@"Filters"])
        {
            self.Filters = (ArrayOfStaffFilter*)[__request createObject:[Helper getNode:__node name:@"Filters"] type:[ArrayOfStaffFilter class]];
        }
        if([Helper hasValue:__node name:@"SessionTypeID"])
        {
            self.SessionTypeID = [[Helper getNode:__node name:@"SessionTypeID"] stringValue];
        }
        if([Helper hasValue:__node name:@"StartDateTime"])
        {
            self.StartDateTime = [[Helper getNode:__node name:@"StartDateTime"] stringValue];
        }
        if([Helper hasValue:__node name:@"LocationID"])
        {
            self.LocationID = [[Helper getNode:__node name:@"LocationID"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __StaffIDsItemElement=[__request writeElement:StaffIDs type:[ArrayOfLong class] name:@"StaffIDs" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StaffIDsItemElement!=nil)
        {
            [self.StaffIDs serialize:__StaffIDsItemElement __request: __request];
        }
             
        DDXMLElement* __StaffCredentialsItemElement=[__request writeElement:StaffCredentials type:[StaffCredentials class] name:@"StaffCredentials" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StaffCredentialsItemElement!=nil)
        {
            [self.StaffCredentials serialize:__StaffCredentialsItemElement __request: __request];
        }
             
        DDXMLElement* __FiltersItemElement=[__request writeElement:Filters type:[ArrayOfStaffFilter class] name:@"Filters" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__FiltersItemElement!=nil)
        {
            [self.Filters serialize:__FiltersItemElement __request: __request];
        }
             
        DDXMLElement* __SessionTypeIDItemElement=[__request writeElement:SessionTypeID type:[NSString class] name:@"SessionTypeID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__SessionTypeIDItemElement!=nil)
        {
            [__SessionTypeIDItemElement setStringValue:self.SessionTypeID];
        }
             
        DDXMLElement* __StartDateTimeItemElement=[__request writeElement:StartDateTime type:[NSString class] name:@"StartDateTime" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StartDateTimeItemElement!=nil)
        {
            [__StartDateTimeItemElement setStringValue:self.StartDateTime];
        }
             
        DDXMLElement* __LocationIDItemElement=[__request writeElement:LocationID type:[NSString class] name:@"LocationID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LocationIDItemElement!=nil)
        {
            [__LocationIDItemElement setStringValue:self.LocationID];
        }


}
@end
