//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class ArrayOfLong;
@class StaffCredentials;
@class ArrayOfStaffFilter;
#import "MBRequest.h"
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface GetStaffRequest : MBRequest 


@property (retain,nonatomic,getter=getStaffIDs) ArrayOfLong* StaffIDs;

@property (retain,nonatomic,getter=getStaffCredentials) StaffCredentials* StaffCredentials;

@property (retain,nonatomic,getter=getFilters) ArrayOfStaffFilter* Filters;

@property (retain,nonatomic,getter=getSessionTypeID) NSString* SessionTypeID;

@property (retain,nonatomic,getter=getStartDateTime) NSString* StartDateTime;

@property (retain,nonatomic,getter=getLocationID) NSString* LocationID;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(GetStaffRequest*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end