//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "ArrayOfInt.h"
#import "ArrayOfLong.h"
#import "MBRequest.h"
#import "Helper.h"
#import "GetScheduleItemsRequest.h"


@implementation GetScheduleItemsRequest
    @synthesize LocationIDs;
    @synthesize StaffIDs;
    @synthesize StartDate;
    @synthesize EndDate;
    @synthesize IgnorePrepFinishTimes;

+ (GetScheduleItemsRequest *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"LocationIDs"])
        {
            self.LocationIDs = (ArrayOfInt*)[__request createObject:[Helper getNode:__node name:@"LocationIDs"] type:[ArrayOfInt class]];
        }
        if([Helper hasValue:__node name:@"StaffIDs"])
        {
            self.StaffIDs = (ArrayOfLong*)[__request createObject:[Helper getNode:__node name:@"StaffIDs"] type:[ArrayOfLong class]];
        }
        if([Helper hasValue:__node name:@"StartDate"])
        {
            self.StartDate = [[Helper getNode:__node name:@"StartDate"] stringValue];
        }
        if([Helper hasValue:__node name:@"EndDate"])
        {
            self.EndDate = [[Helper getNode:__node name:@"EndDate"] stringValue];
        }
        if([Helper hasValue:__node name:@"IgnorePrepFinishTimes"])
        {
            self.IgnorePrepFinishTimes = [[Helper getNode:__node name:@"IgnorePrepFinishTimes"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __LocationIDsItemElement=[__request writeElement:LocationIDs type:[ArrayOfInt class] name:@"LocationIDs" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LocationIDsItemElement!=nil)
        {
            [self.LocationIDs serialize:__LocationIDsItemElement __request: __request];
        }
             
        DDXMLElement* __StaffIDsItemElement=[__request writeElement:StaffIDs type:[ArrayOfLong class] name:@"StaffIDs" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StaffIDsItemElement!=nil)
        {
            [self.StaffIDs serialize:__StaffIDsItemElement __request: __request];
        }
             
        DDXMLElement* __StartDateItemElement=[__request writeElement:StartDate type:[NSString class] name:@"StartDate" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StartDateItemElement!=nil)
        {
            [__StartDateItemElement setStringValue:self.StartDate];
        }
             
        DDXMLElement* __EndDateItemElement=[__request writeElement:EndDate type:[NSString class] name:@"EndDate" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EndDateItemElement!=nil)
        {
            [__EndDateItemElement setStringValue:self.EndDate];
        }
             
        DDXMLElement* __IgnorePrepFinishTimesItemElement=[__request writeElement:IgnorePrepFinishTimes type:[NSString class] name:@"IgnorePrepFinishTimes" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IgnorePrepFinishTimesItemElement!=nil)
        {
            [__IgnorePrepFinishTimesItemElement setStringValue:self.IgnorePrepFinishTimes];
        }


}
@end
