//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "MBResult.h"
#import "Helper.h"
#import "GetStaffImgURLResult.h"


@implementation GetStaffImgURLResult
    @synthesize ImageURL;
    @synthesize MobileImageURL;

+ (GetStaffImgURLResult *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"ImageURL"])
        {
            self.ImageURL = [[Helper getNode:__node name:@"ImageURL"] stringValue];
        }
        if([Helper hasValue:__node name:@"MobileImageURL"])
        {
            self.MobileImageURL = [[Helper getNode:__node name:@"MobileImageURL"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __ImageURLItemElement=[__request writeElement:ImageURL type:[NSString class] name:@"ImageURL" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ImageURLItemElement!=nil)
        {
            [__ImageURLItemElement setStringValue:self.ImageURL];
        }
             
        DDXMLElement* __MobileImageURLItemElement=[__request writeElement:MobileImageURL type:[NSString class] name:@"MobileImageURL" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__MobileImageURLItemElement!=nil)
        {
            [__MobileImageURLItemElement setStringValue:self.MobileImageURL];
        }


}
@end
