//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class StaffCredentials;
@class ArrayOfInt;
@class ArrayOfLong;
@class ArrayOfString;
#import "MBRequest.h"
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface GetStaffAppointmentsRequest : MBRequest 


@property (retain,nonatomic,getter=getStaffCredentials) StaffCredentials* StaffCredentials;

@property (retain,nonatomic,getter=getAppointmentIDs) ArrayOfInt* AppointmentIDs;

@property (retain,nonatomic,getter=getLocationIDs) ArrayOfInt* LocationIDs;

@property (retain,nonatomic,getter=getStartDate) NSString* StartDate;

@property (retain,nonatomic,getter=getEndDate) NSString* EndDate;

@property (retain,nonatomic,getter=getStaffIDs) ArrayOfLong* StaffIDs;

@property (retain,nonatomic,getter=getClientIDs) ArrayOfString* ClientIDs;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(GetStaffAppointmentsRequest*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end