//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------
  
#import "Helper.h"

@implementation Helper

+(DDXMLElement*) getResultElement: (DDXMLElement*) body name:(NSString*)name
{
    DDXMLElement* resultElement=(DDXMLElement*)[body childAtIndex:0];
    if([resultElement childCount]>0)
    {
        DDXMLElement* propertyElement=(DDXMLElement*)[resultElement childAtIndex:0];
        if([propertyElement.localName isEqualToString:name])
        {
            return propertyElement;
        }
        if([resultElement.localName isEqualToString:name])
        {
            return resultElement;
        }
    }
    return body;
}


+(DDXMLElement*) getNode:(DDXMLElement *) node name:(NSString*) name URI:(NSString*) URI
{
    NSArray *items= [node elementsForLocalName:name URI:URI];
    if([items count]>0)
    {
        return [items objectAtIndex:0];
    }
    return nil;
}

+(DDXMLNode*) getAttribute:(DDXMLElement *)node name:(NSString *)name
{
    return [node attributeForName: name];
}

+(DDXMLElement*) getNode:(DDXMLElement *)node name:(NSString *)name
{
    NSArray *items= [node elementsForName:name];
    if([items count]>0)
    {
        DDXMLElement *element= [items objectAtIndex:0];
        return element;
    }
    return nil;
}

+(BOOL) hasAttribute:(DDXMLElement*) node name:(NSString*)name
{
    DDXMLNode* child=[Helper getAttribute:node name:name];
    return child!=nil;
}

+(BOOL) hasValue:(DDXMLElement*) node name:(NSString*)name
{
    DDXMLElement* child=[Helper getNode:node name:name];
    if(child!=nil)
    {
        DDXMLNode* nilAttr=[Helper getAttribute:child name:@"nil" url:XSI];
        return nilAttr==nil;
    }
    return NO;
}


+(DDXMLNode*) getAttribute:(DDXMLElement*) node name:(NSString*)name url:(NSString*) url
{
    NSString * fullName=name;
    NSString* prefix=[node resolvePrefixForNamespaceURI:url];
    if([prefix length]>0)
    {
        fullName=[prefix stringByAppendingFormat:@":%@",name];
    }
    DDXMLNode * typeAttr=[node attributeForName:fullName];
    return typeAttr;
}
@end