//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
#import "DDXML.h"
    
#define MS_SERIALIZATION_NS @"http://schemas.microsoft.com/2003/10/Serialization/"
#define XSI @"http://www.w3.org/2001/XMLSchema-instance"

@interface Helper : NSObject
    
+(DDXMLElement*) getResultElement: (DDXMLElement*) body name:(NSString*)name;
+(DDXMLElement*) getNode:(DDXMLElement*) node name:(NSString*)name;
+(DDXMLElement*) getNode:(DDXMLElement *) node name:(NSString*) name URI:(NSString*) URI;
+(BOOL) hasAttribute:(DDXMLElement*) node name:(NSString*)name;
+(DDXMLNode*) getAttribute:(DDXMLElement *)node name:(NSString *)name;
+(BOOL) hasValue:(DDXMLElement*) node name:(NSString*)name;
+(DDXMLNode*) getAttribute:(DDXMLElement*) node name:(NSString*)name url:(NSString*) url;
@end