//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class ArrayOfString;
#import "MBObject.h"
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface Location : MBObject 


@property (retain,nonatomic,getter=getBusinessID) NSString* BusinessID;

@property (retain,nonatomic,getter=getSiteID) NSString* SiteID;

@property (retain,nonatomic,getter=getBusinessDescription) NSString* BusinessDescription;

@property (retain,nonatomic,getter=getAdditionalImageURLs) ArrayOfString* AdditionalImageURLs;

@property (retain,nonatomic,getter=getFacilitySquareFeet) NSString* FacilitySquareFeet;

@property (retain,nonatomic,getter=getTreatmentRooms) NSString* TreatmentRooms;

@property (retain,nonatomic,getter=getProSpaFinderSite) NSString* ProSpaFinderSite;

@property (retain,nonatomic,getter=getHasClasses) NSString* HasClasses;

@property (retain,nonatomic,getter=getPhoneExtension) NSString* PhoneExtension;

@property (retain,nonatomic,getter=getAction) NSString* Action;

@property (retain,nonatomic,getter=getID) NSString* ID;

@property (retain,nonatomic,getter=getName) NSString* Name;

@property (retain,nonatomic,getter=getAddress) NSString* Address;

@property (retain,nonatomic,getter=getAddress2) NSString* Address2;

@property (retain,nonatomic,getter=getTax1) NSString* Tax1;

@property (retain,nonatomic,getter=getTax2) NSString* Tax2;

@property (retain,nonatomic,getter=getTax3) NSString* Tax3;

@property (retain,nonatomic,getter=getTax4) NSString* Tax4;

@property (retain,nonatomic,getter=getTax5) NSString* Tax5;

@property (retain,nonatomic,getter=getPhone) NSString* Phone;

@property (retain,nonatomic,getter=getCity) NSString* City;

@property (retain,nonatomic,getter=getStateProvCode) NSString* StateProvCode;

@property (retain,nonatomic,getter=getPostalCode) NSString* PostalCode;

@property (retain,nonatomic,getter=getLatitude) NSString* Latitude;

@property (retain,nonatomic,getter=getLongitude) NSString* Longitude;

@property (retain,nonatomic,getter=getDistanceInMiles) NSString* DistanceInMiles;

@property (retain,nonatomic,getter=getImageURL) NSString* ImageURL;

@property (retain,nonatomic,getter=getDescription) NSString* Description;

@property (retain,nonatomic,getter=getHasSite) NSString* HasSite;

@property (retain,nonatomic,getter=getCanBook) NSString* CanBook;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(Location*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end