//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class Site;
@class ArrayOfString;
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface MBObject : NSObject 


@property (retain,nonatomic,getter=getSite) Site* Site;

@property (retain,nonatomic,getter=getMessages) ArrayOfString* Messages;

@property (retain,nonatomic,getter=getExecute) NSString* Execute;

@property (retain,nonatomic,getter=getErrorCode) NSString* ErrorCode;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(MBObject*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end