//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "SourceCredentials.h"
#import "UserCredentials.h"
#import "ArrayOfString.h"
#import "Helper.h"
#import "MBRequest.h"


@implementation MBRequest
    @synthesize SourceCredentials;
    @synthesize UserCredentials;
    @synthesize XMLDetail;
    @synthesize PageSize;
    @synthesize CurrentPageIndex;
    @synthesize Fields;

+ (MBRequest *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"SourceCredentials"])
        {
            self.SourceCredentials = (SourceCredentials*)[__request createObject:[Helper getNode:__node name:@"SourceCredentials"] type:[SourceCredentials class]];
        }
        if([Helper hasValue:__node name:@"UserCredentials"])
        {
            self.UserCredentials = (UserCredentials*)[__request createObject:[Helper getNode:__node name:@"UserCredentials"] type:[UserCredentials class]];
        }
        if([Helper hasValue:__node name:@"XMLDetail"])
        {
            self.XMLDetail = [[Helper getNode:__node name:@"XMLDetail"] stringValue];
        }
        if([Helper hasValue:__node name:@"PageSize"])
        {
            self.PageSize = [[Helper getNode:__node name:@"PageSize"] stringValue];
        }
        if([Helper hasValue:__node name:@"CurrentPageIndex"])
        {
            self.CurrentPageIndex = [[Helper getNode:__node name:@"CurrentPageIndex"] stringValue];
        }
        if([Helper hasValue:__node name:@"Fields"])
        {
            self.Fields = (ArrayOfString*)[__request createObject:[Helper getNode:__node name:@"Fields"] type:[ArrayOfString class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
        DDXMLElement* __SourceCredentialsItemElement=[__request writeElement:SourceCredentials type:[SourceCredentials class] name:@"SourceCredentials" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__SourceCredentialsItemElement!=nil)
        {
            [self.SourceCredentials serialize:__SourceCredentialsItemElement __request: __request];
        }
             
        DDXMLElement* __UserCredentialsItemElement=[__request writeElement:UserCredentials type:[UserCredentials class] name:@"UserCredentials" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__UserCredentialsItemElement!=nil)
        {
            [self.UserCredentials serialize:__UserCredentialsItemElement __request: __request];
        }
             
        DDXMLElement* __XMLDetailItemElement=[__request writeElement:XMLDetail type:[NSString class] name:@"XMLDetail" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__XMLDetailItemElement!=nil)
        {
            [__XMLDetailItemElement setStringValue:self.XMLDetail];
        }
             
        DDXMLElement* __PageSizeItemElement=[__request writeElement:PageSize type:[NSString class] name:@"PageSize" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PageSizeItemElement!=nil)
        {
            [__PageSizeItemElement setStringValue:self.PageSize];
        }
             
        DDXMLElement* __CurrentPageIndexItemElement=[__request writeElement:CurrentPageIndex type:[NSString class] name:@"CurrentPageIndex" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CurrentPageIndexItemElement!=nil)
        {
            [__CurrentPageIndexItemElement setStringValue:self.CurrentPageIndex];
        }
             
        DDXMLElement* __FieldsItemElement=[__request writeElement:Fields type:[ArrayOfString class] name:@"Fields" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__FieldsItemElement!=nil)
        {
            [self.Fields serialize:__FieldsItemElement __request: __request];
        }


}
@end
