//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class SourceCredentials;
@class UserCredentials;
@class ArrayOfString;
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface MBRequest : NSObject 


@property (retain,nonatomic,getter=getSourceCredentials) SourceCredentials* SourceCredentials;

@property (retain,nonatomic,getter=getUserCredentials) UserCredentials* UserCredentials;

@property (retain,nonatomic,getter=getXMLDetail) NSString* XMLDetail;

@property (retain,nonatomic,getter=getPageSize) NSString* PageSize;

@property (retain,nonatomic,getter=getCurrentPageIndex) NSString* CurrentPageIndex;

@property (retain,nonatomic,getter=getFields) ArrayOfString* Fields;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(MBRequest*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end