//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "MBObject.h"
#import "Helper.h"
#import "Program.h"


@implementation Program
    @synthesize ID;
    @synthesize Name;
    @synthesize ScheduleType;

+ (Program *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"ID"])
        {
            self.ID = [[Helper getNode:__node name:@"ID"] stringValue];
        }
        if([Helper hasValue:__node name:@"Name"])
        {
            self.Name = [[Helper getNode:__node name:@"Name"] stringValue];
        }
        if([Helper hasValue:__node name:@"ScheduleType"])
        {
            self.ScheduleType = [[Helper getNode:__node name:@"ScheduleType"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __IDItemElement=[__request writeElement:ID type:[NSString class] name:@"ID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IDItemElement!=nil)
        {
            [__IDItemElement setStringValue:self.ID];
        }
             
        DDXMLElement* __NameItemElement=[__request writeElement:Name type:[NSString class] name:@"Name" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__NameItemElement!=nil)
        {
            [__NameItemElement setStringValue:self.Name];
        }
             
        DDXMLElement* __ScheduleTypeItemElement=[__request writeElement:ScheduleType type:[NSString class] name:@"ScheduleType" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ScheduleTypeItemElement!=nil)
        {
            [__ScheduleTypeItemElement setStringValue:self.ScheduleType];
        }


}
@end
