//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "RequestResultHandler.h"
#import "DDXML.h"



@interface Relationship : NSObject 


@property (retain,nonatomic,getter=getID) NSString* ID;

@property (retain,nonatomic,getter=getRelationshipName1) NSString* RelationshipName1;

@property (retain,nonatomic,getter=getRelationshipName2) NSString* RelationshipName2;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(Relationship*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end