//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "Helper.h"
#import "Relationship.h"


@implementation Relationship
    @synthesize ID;
    @synthesize RelationshipName1;
    @synthesize RelationshipName2;

+ (Relationship *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"ID"])
        {
            self.ID = [[Helper getNode:__node name:@"ID"] stringValue];
        }
        if([Helper hasValue:__node name:@"RelationshipName1"])
        {
            self.RelationshipName1 = [[Helper getNode:__node name:@"RelationshipName1"] stringValue];
        }
        if([Helper hasValue:__node name:@"RelationshipName2"])
        {
            self.RelationshipName2 = [[Helper getNode:__node name:@"RelationshipName2"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
        DDXMLElement* __IDItemElement=[__request writeElement:ID type:[NSString class] name:@"ID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IDItemElement!=nil)
        {
            [__IDItemElement setStringValue:self.ID];
        }
             
        DDXMLElement* __RelationshipName1ItemElement=[__request writeElement:RelationshipName1 type:[NSString class] name:@"RelationshipName1" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__RelationshipName1ItemElement!=nil)
        {
            [__RelationshipName1ItemElement setStringValue:self.RelationshipName1];
        }
             
        DDXMLElement* __RelationshipName2ItemElement=[__request writeElement:RelationshipName2 type:[NSString class] name:@"RelationshipName2" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__RelationshipName2ItemElement!=nil)
        {
            [__RelationshipName2ItemElement setStringValue:self.RelationshipName2];
        }


}
@end
