//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "MBObject.h"
#import "Helper.h"
#import "SessionType.h"


@implementation SessionType
    @synthesize DefaultTimeLength;
    @synthesize ProgramID;
    @synthesize Action;
    @synthesize ID;
    @synthesize Name;

+ (SessionType *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"DefaultTimeLength"])
        {
            self.DefaultTimeLength = [[Helper getNode:__node name:@"DefaultTimeLength"] stringValue];
        }
        if([Helper hasValue:__node name:@"ProgramID"])
        {
            self.ProgramID = [[Helper getNode:__node name:@"ProgramID"] stringValue];
        }
        if([Helper hasValue:__node name:@"Action"])
        {
            self.Action = [[Helper getNode:__node name:@"Action"] stringValue];
        }
        if([Helper hasValue:__node name:@"ID"])
        {
            self.ID = [[Helper getNode:__node name:@"ID"] stringValue];
        }
        if([Helper hasValue:__node name:@"Name"])
        {
            self.Name = [[Helper getNode:__node name:@"Name"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __DefaultTimeLengthItemElement=[__request writeElement:DefaultTimeLength type:[NSString class] name:@"DefaultTimeLength" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__DefaultTimeLengthItemElement!=nil)
        {
            [__DefaultTimeLengthItemElement setStringValue:self.DefaultTimeLength];
        }
             
        DDXMLElement* __ProgramIDItemElement=[__request writeElement:ProgramID type:[NSString class] name:@"ProgramID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ProgramIDItemElement!=nil)
        {
            [__ProgramIDItemElement setStringValue:self.ProgramID];
        }
             
        DDXMLElement* __ActionItemElement=[__request writeElement:Action type:[NSString class] name:@"Action" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ActionItemElement!=nil)
        {
            [__ActionItemElement setStringValue:self.Action];
        }
             
        DDXMLElement* __IDItemElement=[__request writeElement:ID type:[NSString class] name:@"ID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IDItemElement!=nil)
        {
            [__IDItemElement setStringValue:self.ID];
        }
             
        DDXMLElement* __NameItemElement=[__request writeElement:Name type:[NSString class] name:@"Name" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__NameItemElement!=nil)
        {
            [__NameItemElement setStringValue:self.Name];
        }


}
@end
