//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "MBObject.h"
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface SessionType : MBObject 


@property (retain,nonatomic,getter=getDefaultTimeLength) NSString* DefaultTimeLength;

@property (retain,nonatomic,getter=getProgramID) NSString* ProgramID;

@property (retain,nonatomic,getter=getAction) NSString* Action;

@property (retain,nonatomic,getter=getID) NSString* ID;

@property (retain,nonatomic,getter=getName) NSString* Name;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(SessionType*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end