//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "RequestResultHandler.h"
#import "DDXML.h"



@interface Site : NSObject 


@property (retain,nonatomic,getter=getID) NSString* ID;

@property (retain,nonatomic,getter=getName) NSString* Name;

@property (retain,nonatomic,getter=getDescription) NSString* Description;

@property (retain,nonatomic,getter=getLogoURL) NSString* LogoURL;

@property (retain,nonatomic,getter=getPageColor1) NSString* PageColor1;

@property (retain,nonatomic,getter=getPageColor2) NSString* PageColor2;

@property (retain,nonatomic,getter=getPageColor3) NSString* PageColor3;

@property (retain,nonatomic,getter=getPageColor4) NSString* PageColor4;

@property (retain,nonatomic,getter=getAcceptsVisa) NSString* AcceptsVisa;

@property (retain,nonatomic,getter=getAcceptsDiscover) NSString* AcceptsDiscover;

@property (retain,nonatomic,getter=getAcceptsMasterCard) NSString* AcceptsMasterCard;

@property (retain,nonatomic,getter=getAcceptsAmericanExpress) NSString* AcceptsAmericanExpress;

@property (retain,nonatomic,getter=getContactEmail) NSString* ContactEmail;

@property (retain,nonatomic,getter=getESA) NSString* ESA;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(Site*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end