//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "Helper.h"
#import "Site.h"


@implementation Site
    @synthesize ID;
    @synthesize Name;
    @synthesize Description;
    @synthesize LogoURL;
    @synthesize PageColor1;
    @synthesize PageColor2;
    @synthesize PageColor3;
    @synthesize PageColor4;
    @synthesize AcceptsVisa;
    @synthesize AcceptsDiscover;
    @synthesize AcceptsMasterCard;
    @synthesize AcceptsAmericanExpress;
    @synthesize ContactEmail;
    @synthesize ESA;

+ (Site *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [self init])
    {
        if([Helper hasValue:__node name:@"ID"])
        {
            self.ID = [[Helper getNode:__node name:@"ID"] stringValue];
        }
        if([Helper hasValue:__node name:@"Name"])
        {
            self.Name = [[Helper getNode:__node name:@"Name"] stringValue];
        }
        if([Helper hasValue:__node name:@"Description"])
        {
            self.Description = [[Helper getNode:__node name:@"Description"] stringValue];
        }
        if([Helper hasValue:__node name:@"LogoURL"])
        {
            self.LogoURL = [[Helper getNode:__node name:@"LogoURL"] stringValue];
        }
        if([Helper hasValue:__node name:@"PageColor1"])
        {
            self.PageColor1 = [[Helper getNode:__node name:@"PageColor1"] stringValue];
        }
        if([Helper hasValue:__node name:@"PageColor2"])
        {
            self.PageColor2 = [[Helper getNode:__node name:@"PageColor2"] stringValue];
        }
        if([Helper hasValue:__node name:@"PageColor3"])
        {
            self.PageColor3 = [[Helper getNode:__node name:@"PageColor3"] stringValue];
        }
        if([Helper hasValue:__node name:@"PageColor4"])
        {
            self.PageColor4 = [[Helper getNode:__node name:@"PageColor4"] stringValue];
        }
        if([Helper hasValue:__node name:@"AcceptsVisa"])
        {
            self.AcceptsVisa = [[Helper getNode:__node name:@"AcceptsVisa"] stringValue];
        }
        if([Helper hasValue:__node name:@"AcceptsDiscover"])
        {
            self.AcceptsDiscover = [[Helper getNode:__node name:@"AcceptsDiscover"] stringValue];
        }
        if([Helper hasValue:__node name:@"AcceptsMasterCard"])
        {
            self.AcceptsMasterCard = [[Helper getNode:__node name:@"AcceptsMasterCard"] stringValue];
        }
        if([Helper hasValue:__node name:@"AcceptsAmericanExpress"])
        {
            self.AcceptsAmericanExpress = [[Helper getNode:__node name:@"AcceptsAmericanExpress"] stringValue];
        }
        if([Helper hasValue:__node name:@"ContactEmail"])
        {
            self.ContactEmail = [[Helper getNode:__node name:@"ContactEmail"] stringValue];
        }
        if([Helper hasValue:__node name:@"ESA"])
        {
            self.ESA = [[Helper getNode:__node name:@"ESA"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{

             
        DDXMLElement* __IDItemElement=[__request writeElement:ID type:[NSString class] name:@"ID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IDItemElement!=nil)
        {
            [__IDItemElement setStringValue:self.ID];
        }
             
        DDXMLElement* __NameItemElement=[__request writeElement:Name type:[NSString class] name:@"Name" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__NameItemElement!=nil)
        {
            [__NameItemElement setStringValue:self.Name];
        }
             
        DDXMLElement* __DescriptionItemElement=[__request writeElement:Description type:[NSString class] name:@"Description" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__DescriptionItemElement!=nil)
        {
            [__DescriptionItemElement setStringValue:self.Description];
        }
             
        DDXMLElement* __LogoURLItemElement=[__request writeElement:LogoURL type:[NSString class] name:@"LogoURL" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LogoURLItemElement!=nil)
        {
            [__LogoURLItemElement setStringValue:self.LogoURL];
        }
             
        DDXMLElement* __PageColor1ItemElement=[__request writeElement:PageColor1 type:[NSString class] name:@"PageColor1" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PageColor1ItemElement!=nil)
        {
            [__PageColor1ItemElement setStringValue:self.PageColor1];
        }
             
        DDXMLElement* __PageColor2ItemElement=[__request writeElement:PageColor2 type:[NSString class] name:@"PageColor2" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PageColor2ItemElement!=nil)
        {
            [__PageColor2ItemElement setStringValue:self.PageColor2];
        }
             
        DDXMLElement* __PageColor3ItemElement=[__request writeElement:PageColor3 type:[NSString class] name:@"PageColor3" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PageColor3ItemElement!=nil)
        {
            [__PageColor3ItemElement setStringValue:self.PageColor3];
        }
             
        DDXMLElement* __PageColor4ItemElement=[__request writeElement:PageColor4 type:[NSString class] name:@"PageColor4" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PageColor4ItemElement!=nil)
        {
            [__PageColor4ItemElement setStringValue:self.PageColor4];
        }
             
        DDXMLElement* __AcceptsVisaItemElement=[__request writeElement:AcceptsVisa type:[NSString class] name:@"AcceptsVisa" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AcceptsVisaItemElement!=nil)
        {
            [__AcceptsVisaItemElement setStringValue:self.AcceptsVisa];
        }
             
        DDXMLElement* __AcceptsDiscoverItemElement=[__request writeElement:AcceptsDiscover type:[NSString class] name:@"AcceptsDiscover" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AcceptsDiscoverItemElement!=nil)
        {
            [__AcceptsDiscoverItemElement setStringValue:self.AcceptsDiscover];
        }
             
        DDXMLElement* __AcceptsMasterCardItemElement=[__request writeElement:AcceptsMasterCard type:[NSString class] name:@"AcceptsMasterCard" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AcceptsMasterCardItemElement!=nil)
        {
            [__AcceptsMasterCardItemElement setStringValue:self.AcceptsMasterCard];
        }
             
        DDXMLElement* __AcceptsAmericanExpressItemElement=[__request writeElement:AcceptsAmericanExpress type:[NSString class] name:@"AcceptsAmericanExpress" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AcceptsAmericanExpressItemElement!=nil)
        {
            [__AcceptsAmericanExpressItemElement setStringValue:self.AcceptsAmericanExpress];
        }
             
        DDXMLElement* __ContactEmailItemElement=[__request writeElement:ContactEmail type:[NSString class] name:@"ContactEmail" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ContactEmailItemElement!=nil)
        {
            [__ContactEmailItemElement setStringValue:self.ContactEmail];
        }
             
        DDXMLElement* __ESAItemElement=[__request writeElement:ESA type:[NSString class] name:@"ESA" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ESAItemElement!=nil)
        {
            [__ESAItemElement setStringValue:self.ESA];
        }


}
@end
