//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class ArrayOfAppointment;
@class ArrayOfUnavailability;
@class ArrayOfAvailability;
@class ArrayOfLocation;
#import "MBObject.h"
#import "RequestResultHandler.h"
#import "DDXML.h"



@interface Staff : MBObject 


@property (retain,nonatomic,getter=getAppointments) ArrayOfAppointment* Appointments;

@property (retain,nonatomic,getter=getUnavailabilities) ArrayOfUnavailability* Unavailabilities;

@property (retain,nonatomic,getter=getAvailabilities) ArrayOfAvailability* Availabilities;

@property (retain,nonatomic,getter=getEmail) NSString* Email;

@property (retain,nonatomic,getter=getMobilePhone) NSString* MobilePhone;

@property (retain,nonatomic,getter=getHomePhone) NSString* HomePhone;

@property (retain,nonatomic,getter=getWorkPhone) NSString* WorkPhone;

@property (retain,nonatomic,getter=getAddress) NSString* Address;

@property (retain,nonatomic,getter=getAddress2) NSString* Address2;

@property (retain,nonatomic,getter=getCity) NSString* City;

@property (retain,nonatomic,getter=getState) NSString* State;

@property (retain,nonatomic,getter=getCountry) NSString* Country;

@property (retain,nonatomic,getter=getPostalCode) NSString* PostalCode;

@property (retain,nonatomic,getter=getForeignZip) NSString* ForeignZip;

@property (retain,nonatomic,getter=getLoginLocations) ArrayOfLocation* LoginLocations;

@property (retain,nonatomic,getter=getAction) NSString* Action;

@property (retain,nonatomic,getter=getID) NSString* ID;

@property (retain,nonatomic,getter=getName) NSString* Name;

@property (retain,nonatomic,getter=getFirstName) NSString* FirstName;

@property (retain,nonatomic,getter=getLastName) NSString* LastName;

@property (retain,nonatomic,getter=getImageURL) NSString* ImageURL;

@property (retain,nonatomic,getter=getBio) NSString* Bio;

@property (retain,nonatomic,getter=getIsMale) NSString* isMale;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(RequestResultHandler*) __request;
+(Staff*) createWithXml:(DDXMLElement*)__node __request:(RequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request;
@end