//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "ArrayOfAppointment.h"
#import "ArrayOfUnavailability.h"
#import "ArrayOfAvailability.h"
#import "ArrayOfLocation.h"
#import "MBObject.h"
#import "Helper.h"
#import "Staff.h"


@implementation Staff
    @synthesize Appointments;
    @synthesize Unavailabilities;
    @synthesize Availabilities;
    @synthesize Email;
    @synthesize MobilePhone;
    @synthesize HomePhone;
    @synthesize WorkPhone;
    @synthesize Address;
    @synthesize Address2;
    @synthesize City;
    @synthesize State;
    @synthesize Country;
    @synthesize PostalCode;
    @synthesize ForeignZip;
    @synthesize LoginLocations;
    @synthesize Action;
    @synthesize ID;
    @synthesize Name;
    @synthesize FirstName;
    @synthesize LastName;
    @synthesize ImageURL;
    @synthesize Bio;
    @synthesize isMale;

+ (Staff *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"Appointments"])
        {
            self.Appointments = (ArrayOfAppointment*)[__request createObject:[Helper getNode:__node name:@"Appointments"] type:[ArrayOfAppointment class]];
        }
        if([Helper hasValue:__node name:@"Unavailabilities"])
        {
            self.Unavailabilities = (ArrayOfUnavailability*)[__request createObject:[Helper getNode:__node name:@"Unavailabilities"] type:[ArrayOfUnavailability class]];
        }
        if([Helper hasValue:__node name:@"Availabilities"])
        {
            self.Availabilities = (ArrayOfAvailability*)[__request createObject:[Helper getNode:__node name:@"Availabilities"] type:[ArrayOfAvailability class]];
        }
        if([Helper hasValue:__node name:@"Email"])
        {
            self.Email = [[Helper getNode:__node name:@"Email"] stringValue];
        }
        if([Helper hasValue:__node name:@"MobilePhone"])
        {
            self.MobilePhone = [[Helper getNode:__node name:@"MobilePhone"] stringValue];
        }
        if([Helper hasValue:__node name:@"HomePhone"])
        {
            self.HomePhone = [[Helper getNode:__node name:@"HomePhone"] stringValue];
        }
        if([Helper hasValue:__node name:@"WorkPhone"])
        {
            self.WorkPhone = [[Helper getNode:__node name:@"WorkPhone"] stringValue];
        }
        if([Helper hasValue:__node name:@"Address"])
        {
            self.Address = [[Helper getNode:__node name:@"Address"] stringValue];
        }
        if([Helper hasValue:__node name:@"Address2"])
        {
            self.Address2 = [[Helper getNode:__node name:@"Address2"] stringValue];
        }
        if([Helper hasValue:__node name:@"City"])
        {
            self.City = [[Helper getNode:__node name:@"City"] stringValue];
        }
        if([Helper hasValue:__node name:@"State"])
        {
            self.State = [[Helper getNode:__node name:@"State"] stringValue];
        }
        if([Helper hasValue:__node name:@"Country"])
        {
            self.Country = [[Helper getNode:__node name:@"Country"] stringValue];
        }
        if([Helper hasValue:__node name:@"PostalCode"])
        {
            self.PostalCode = [[Helper getNode:__node name:@"PostalCode"] stringValue];
        }
        if([Helper hasValue:__node name:@"ForeignZip"])
        {
            self.ForeignZip = [[Helper getNode:__node name:@"ForeignZip"] stringValue];
        }
        if([Helper hasValue:__node name:@"LoginLocations"])
        {
            self.LoginLocations = (ArrayOfLocation*)[__request createObject:[Helper getNode:__node name:@"LoginLocations"] type:[ArrayOfLocation class]];
        }
        if([Helper hasValue:__node name:@"Action"])
        {
            self.Action = [[Helper getNode:__node name:@"Action"] stringValue];
        }
        if([Helper hasValue:__node name:@"ID"])
        {
            self.ID = [[Helper getNode:__node name:@"ID"] stringValue];
        }
        if([Helper hasValue:__node name:@"Name"])
        {
            self.Name = [[Helper getNode:__node name:@"Name"] stringValue];
        }
        if([Helper hasValue:__node name:@"FirstName"])
        {
            self.FirstName = [[Helper getNode:__node name:@"FirstName"] stringValue];
        }
        if([Helper hasValue:__node name:@"LastName"])
        {
            self.LastName = [[Helper getNode:__node name:@"LastName"] stringValue];
        }
        if([Helper hasValue:__node name:@"ImageURL"])
        {
            self.ImageURL = [[Helper getNode:__node name:@"ImageURL"] stringValue];
        }
        if([Helper hasValue:__node name:@"Bio"])
        {
            self.Bio = [[Helper getNode:__node name:@"Bio"] stringValue];
        }
        if([Helper hasValue:__node name:@"isMale"])
        {
            self.isMale = [[Helper getNode:__node name:@"isMale"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __AppointmentsItemElement=[__request writeElement:Appointments type:[ArrayOfAppointment class] name:@"Appointments" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AppointmentsItemElement!=nil)
        {
            [self.Appointments serialize:__AppointmentsItemElement __request: __request];
        }
             
        DDXMLElement* __UnavailabilitiesItemElement=[__request writeElement:Unavailabilities type:[ArrayOfUnavailability class] name:@"Unavailabilities" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__UnavailabilitiesItemElement!=nil)
        {
            [self.Unavailabilities serialize:__UnavailabilitiesItemElement __request: __request];
        }
             
        DDXMLElement* __AvailabilitiesItemElement=[__request writeElement:Availabilities type:[ArrayOfAvailability class] name:@"Availabilities" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AvailabilitiesItemElement!=nil)
        {
            [self.Availabilities serialize:__AvailabilitiesItemElement __request: __request];
        }
             
        DDXMLElement* __EmailItemElement=[__request writeElement:Email type:[NSString class] name:@"Email" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EmailItemElement!=nil)
        {
            [__EmailItemElement setStringValue:self.Email];
        }
             
        DDXMLElement* __MobilePhoneItemElement=[__request writeElement:MobilePhone type:[NSString class] name:@"MobilePhone" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__MobilePhoneItemElement!=nil)
        {
            [__MobilePhoneItemElement setStringValue:self.MobilePhone];
        }
             
        DDXMLElement* __HomePhoneItemElement=[__request writeElement:HomePhone type:[NSString class] name:@"HomePhone" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__HomePhoneItemElement!=nil)
        {
            [__HomePhoneItemElement setStringValue:self.HomePhone];
        }
             
        DDXMLElement* __WorkPhoneItemElement=[__request writeElement:WorkPhone type:[NSString class] name:@"WorkPhone" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__WorkPhoneItemElement!=nil)
        {
            [__WorkPhoneItemElement setStringValue:self.WorkPhone];
        }
             
        DDXMLElement* __AddressItemElement=[__request writeElement:Address type:[NSString class] name:@"Address" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__AddressItemElement!=nil)
        {
            [__AddressItemElement setStringValue:self.Address];
        }
             
        DDXMLElement* __Address2ItemElement=[__request writeElement:Address2 type:[NSString class] name:@"Address2" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__Address2ItemElement!=nil)
        {
            [__Address2ItemElement setStringValue:self.Address2];
        }
             
        DDXMLElement* __CityItemElement=[__request writeElement:City type:[NSString class] name:@"City" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CityItemElement!=nil)
        {
            [__CityItemElement setStringValue:self.City];
        }
             
        DDXMLElement* __StateItemElement=[__request writeElement:State type:[NSString class] name:@"State" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StateItemElement!=nil)
        {
            [__StateItemElement setStringValue:self.State];
        }
             
        DDXMLElement* __CountryItemElement=[__request writeElement:Country type:[NSString class] name:@"Country" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__CountryItemElement!=nil)
        {
            [__CountryItemElement setStringValue:self.Country];
        }
             
        DDXMLElement* __PostalCodeItemElement=[__request writeElement:PostalCode type:[NSString class] name:@"PostalCode" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__PostalCodeItemElement!=nil)
        {
            [__PostalCodeItemElement setStringValue:self.PostalCode];
        }
             
        DDXMLElement* __ForeignZipItemElement=[__request writeElement:ForeignZip type:[NSString class] name:@"ForeignZip" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ForeignZipItemElement!=nil)
        {
            [__ForeignZipItemElement setStringValue:self.ForeignZip];
        }
             
        DDXMLElement* __LoginLocationsItemElement=[__request writeElement:LoginLocations type:[ArrayOfLocation class] name:@"LoginLocations" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LoginLocationsItemElement!=nil)
        {
            [self.LoginLocations serialize:__LoginLocationsItemElement __request: __request];
        }
             
        DDXMLElement* __ActionItemElement=[__request writeElement:Action type:[NSString class] name:@"Action" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ActionItemElement!=nil)
        {
            [__ActionItemElement setStringValue:self.Action];
        }
             
        DDXMLElement* __IDItemElement=[__request writeElement:ID type:[NSString class] name:@"ID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IDItemElement!=nil)
        {
            [__IDItemElement setStringValue:self.ID];
        }
             
        DDXMLElement* __NameItemElement=[__request writeElement:Name type:[NSString class] name:@"Name" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__NameItemElement!=nil)
        {
            [__NameItemElement setStringValue:self.Name];
        }
             
        DDXMLElement* __FirstNameItemElement=[__request writeElement:FirstName type:[NSString class] name:@"FirstName" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__FirstNameItemElement!=nil)
        {
            [__FirstNameItemElement setStringValue:self.FirstName];
        }
             
        DDXMLElement* __LastNameItemElement=[__request writeElement:LastName type:[NSString class] name:@"LastName" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__LastNameItemElement!=nil)
        {
            [__LastNameItemElement setStringValue:self.LastName];
        }
             
        DDXMLElement* __ImageURLItemElement=[__request writeElement:ImageURL type:[NSString class] name:@"ImageURL" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ImageURLItemElement!=nil)
        {
            [__ImageURLItemElement setStringValue:self.ImageURL];
        }
             
        DDXMLElement* __BioItemElement=[__request writeElement:Bio type:[NSString class] name:@"Bio" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__BioItemElement!=nil)
        {
            [__BioItemElement setStringValue:self.Bio];
        }
             
        DDXMLElement* __isMaleItemElement=[__request writeElement:isMale type:[NSString class] name:@"isMale" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__isMaleItemElement!=nil)
        {
            [__isMaleItemElement setStringValue:self.isMale];
        }


}
@end
