//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "Staff_x005F_x0020_ServiceSoap.h"
#import "RequestResultHandler.h"
#import "Helper.h"

@implementation Staff_x005F_x0020_ServiceSoap
@synthesize Url,ShouldAddAdornments,Headers;

- (id) init {
    if(self = [super init])
    {
        self.Url=@"https://api.mindbodyonline.com/0_5/StaffService.asmx";
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(RequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}



-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) createGetStaffRequest:(GetStaffRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"GetStaff" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[GetStaffRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/GetStaff";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(GetStaffResult*) GetStaff:(GetStaffRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    __request.SkipNullProperties = YES;
    NSMutableURLRequest *__requestObj=[self createGetStaffRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"GetStaffResult"];
    return (GetStaffResult*)[__request createObject:__result type:[GetStaffResult class]];
}
-(NSMutableURLRequest*) createGetStaffPermissionsRequest:(GetStaffPermissionsRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"GetStaffPermissions" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[GetStaffPermissionsRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/GetStaffPermissions";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(GetStaffPermissionsResult*) GetStaffPermissions:(GetStaffPermissionsRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self createGetStaffPermissionsRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"GetStaffPermissionsResult"];
    return (GetStaffPermissionsResult*)[__request createObject:__result type:[GetStaffPermissionsResult class]];
}
-(NSMutableURLRequest*) createAddOrUpdateStaffRequest:(AddOrUpdateStaffRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"AddOrUpdateStaff" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[AddOrUpdateStaffRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/AddOrUpdateStaff";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(AddOrUpdateStaffResult*) AddOrUpdateStaff:(AddOrUpdateStaffRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self createAddOrUpdateStaffRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"AddOrUpdateStaffResult"];
    return (AddOrUpdateStaffResult*)[__request createObject:__result type:[AddOrUpdateStaffResult class]];
}
-(NSMutableURLRequest*) createGetStaffImgURLRequest:(GetStaffImgURLRequest*) Request __request:(RequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"GetStaffImgURL" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __RequestItemElement=[__request writeElement:Request type:[GetStaffImgURLRequest class] name:@"Request" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__RequestItemElement!=nil)
        {
            [Request serialize:__RequestItemElement __request: __request];
        }
    
    NSString* __soapAction=@"http://clients.mindbodyonline.com/api/0_5/GetStaffImgURL";
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}


-(GetStaffImgURLResult*) GetStaffImgURL:(GetStaffImgURLRequest*) Request __error:(NSError**) __error 
{
    RequestResultHandler* __request =[[RequestResultHandler alloc]init];
    NSMutableURLRequest *__requestObj=[self createGetStaffImgURLRequest:Request __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[Helper getResultElement:__request.OutputBody name:@"GetStaffImgURLResult"];
    return (GetStaffImgURLResult*)[__request createObject:__result type:[GetStaffImgURLResult class]];
}

@end
