//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.0.1
//
// Created by Quasar Development at 21-03-2014
//
//---------------------------------------------------


#import "ScheduleItem.h"
#import "Helper.h"
#import "Unavailability.h"


@implementation Unavailability
    @synthesize ID;
    @synthesize StartDateTime;
    @synthesize EndDateTime;
    @synthesize Description;

+ (Unavailability *)createWithXml:(DDXMLElement *)__node __request:(RequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(RequestResultHandler*) __request{
    if(self = [super initWithXml:__node __request:__request])
    {
        if([Helper hasValue:__node name:@"ID"])
        {
            self.ID = [[Helper getNode:__node name:@"ID"] stringValue];
        }
        if([Helper hasValue:__node name:@"StartDateTime"])
        {
            self.StartDateTime = [[Helper getNode:__node name:@"StartDateTime"] stringValue];
        }
        if([Helper hasValue:__node name:@"EndDateTime"])
        {
            self.EndDateTime = [[Helper getNode:__node name:@"EndDateTime"] stringValue];
        }
        if([Helper hasValue:__node name:@"Description"])
        {
            self.Description = [[Helper getNode:__node name:@"Description"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(RequestResultHandler*) __request
{
    [super serialize:__parent __request:__request];

             
        DDXMLElement* __IDItemElement=[__request writeElement:ID type:[NSString class] name:@"ID" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__IDItemElement!=nil)
        {
            [__IDItemElement setStringValue:self.ID];
        }
             
        DDXMLElement* __StartDateTimeItemElement=[__request writeElement:StartDateTime type:[NSString class] name:@"StartDateTime" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__StartDateTimeItemElement!=nil)
        {
            [__StartDateTimeItemElement setStringValue:self.StartDateTime];
        }
             
        DDXMLElement* __EndDateTimeItemElement=[__request writeElement:EndDateTime type:[NSString class] name:@"EndDateTime" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__EndDateTimeItemElement!=nil)
        {
            [__EndDateTimeItemElement setStringValue:self.EndDateTime];
        }
             
        DDXMLElement* __DescriptionItemElement=[__request writeElement:Description type:[NSString class] name:@"Description" URI:@"http://clients.mindbodyonline.com/api/0_5" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__DescriptionItemElement!=nil)
        {
            [__DescriptionItemElement setStringValue:self.Description];
        }


}
@end
